### ISSUE TITLE
ReferenceError: echarts is not defined

### ISSUE THREAD

**Issue by Jmarisa** [xieziyu/ngx-echarts#10]
When I run the page with the chart, it gives me this error:

<img width="948" alt="captura de ecra 2017-06-28 as 15 52 29" src="https://user-images.githubusercontent.com/9882847/27644000-7d8ccc92-5c1a-11e7-8362-c999ced3b566.png">

(I'm importing the script on angular-cli)

Any ideas?

**Comment by xieziyu** [comment]
@Jmarisa 
1. check if you have correctly installed echarts and imported in `.angular-cli.json`
2. check if your project is involved with other module resolver, such as `webpack` or `systemjs`

**Comment by lihuabest** [comment]
我也存在这个问题，换了好多echarts版本 都不行。angular-cli.json里确定是加入了echarts的 死活找不到原因

**Comment by shao37142** [comment]
我也有这个问题...想请教一下,我安装完毕之后ngx-echarts这个文件的directive里面没有angular-echarts.directive..ts文件...但是有一个angular-echarts.directive.d.ts...里面export了AngularEchartsDirective,里面的代码和你的angular-echarts.directive.ts的差很多...所以...怎么办...

**Comment by xieziyu** [comment]
@shao37142 安装后的目录ngx-echarts目录里面，你不需要关心directive目录。
按照README中的说明，根据你的项目类型修改配置即可。

**Comment by shao37142** [comment]
@xieziyu 主要我是小白...想搞明白这个包到底是个什么原理...弄好了,感谢...

**Comment by liusongge** [comment]
在node_modules里新增这个 new webpack.ProvidePlugin({ echarts: 'echarts' }) 的话别人如果下代码更改 每次都要在node里添加这个啊。。 有没有其他的方法可以解决呢

**Comment by liusongge** [comment]
@lihuabest
