### ISSUE TITLE
ngx-echarts  tree怎么阻止点击树的节点后树伸缩的行为？

### ISSUE THREAD

**Issue by guanjingya** [xieziyu/ngx-echarts#107]
目前本项目的需求是点击树的节点后获取该节点的一些数据出现这个节点的详细信息的弹出展示该节点详细信息，目前能点击节点并获得想要的参数，但是点击节点后树会伸缩，请问怎么阻止这个默认行为？

**Comment by xieziyu** [comment]
@guanjingya 这个是echarts本身的行为，你需要去他们的社区平台寻求解决方法:
https://github.com/apache/incubator-echarts
