### ISSUE TITLE
ngx-echarts tree 怎么拿到echarts更新数据setOption

### ISSUE THREAD

**Issue by guanjingya** [xieziyu/ngx-echarts#108]
本项目树下面有一个加载更多的按钮，实现一点击就加载更多层数，默认显示10层。

**Comment by xieziyu** [comment]
@guanjingya 不是太理解你的问题？
如果你指的是点击加载更多的按钮，后让tree显示更多的层，那么就是在加载数据后的用[merge]接口，将更新后的series传入合并

**Comment by guanjingya** [comment]
非常感谢，问题已经解决，用的是[merge]接口。
[merge]接口是setOption(option, notMerge, lazyUpdate); 的notMerge是否不跟之前设置的option进行合并，默认为false，即合并。如果想改成不合并，merge接口没办法实现吧？

**Comment by guanjingya** [comment]
好的，感谢！
