### ISSUE TITLE
echart动画加载不执行

### ISSUE THREAD

**Issue by jsvr** [xieziyu/ngx-echarts#109]
设置echarts的动画:
        largeThreshold: 8000,
        animationThreshold: 8000,
        animationDuration: 8000,
        animationDelay: 200,
不执行, 点击legend 的按钮是动画才执行, 可是同样的设置,在echarts官网demo是有作用的?这个是什么原因?

**Comment by xieziyu** [comment]
@jsvr 将ngx-echarts升级到v2.2.0再试试

**Comment by jsvr** [comment]
解决了 三克油 @xieziyu
