### ISSUE TITLE
echart line real time issue

### ISSUE THREAD

**Issue by jay-aplan** [xieziyu/ngx-echarts#112]
![graph issue](https://user-images.githubusercontent.com/32902481/42346128-82b771e6-8099-11e8-97ff-ad3e1606a622.png)

Hi Guys
Great work with the chart guys! I was trying to use it for real time line chart. Everything is working fine, it is updating properly as well when I update the "data". My only problem is I want to show 30 mins timeline on x-axis with every second details. so I initialised the data with following.. It is correctly populating the chart for 50 seconds but after every 50 sec, it is not filling 10 seconds with 0 zero as shown in the image attached with black circles not sure why ??

    this.TotalMinutesOnGraph = 30;
    for (let i = 0; i < this.TotalMinutesOnGraph * 60 ; i++) { // creating dummy data for 30 minutes
      this.data.push(this.blankData());
    }

blankData() {
    this.now = new Date(this.now.getTime() + 1000);  // increment by 1 second
    this.value = 0;
    return {
      name: this.now.toString(),
      value: [
        [this.now.getFullYear(), this.now.getMonth() + 1, this.now.getDate()].join('/') + ' ' + 
                           this.now.getHours() + ':' + this.now.getMinutes() + ':' + this.now.getSeconds()
           , this.value
      ]
    };
  }

**Comment by xieziyu** [comment]
@jay-aplan 
The issue may be caused by `this.now.getMinutes()` or `this.now.getSeconds()`.

If minute or second was less than 10, your time string might look like: '2018/07/07 19:6:1'. Well as a string, it doesn't equal to '2018/07/07 19:06:01'. So the data won't show up on the axis.

Try to padding your minutes, seconds or any other part with 0.

**Comment by jay-aplan** [comment]
Thanks so much that helped! :)
