### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by xushuo** [xieziyu/ngx-echarts#113]
TypeError: Object(...) is not a function
用的是 angular5 和echarts3 和ngx-echarts3
代码是本网站的demo

**Comment by ZhipengZeng** [comment]
自己解决了，ng5只能用2.2.0版本的

**Comment by xieziyu** [comment]
@ZhipengZeng @xushuo 
对的。
v3.1.0 for Angular >= 6
v2.2.0 for Angular < 6

**Comment by xushuo** [comment]
谢谢

**Comment by writer0713** [comment]
@xieziyu thanks, man :)
