### ISSUE TITLE
this._resize$.pipe is not a function

### ISSUE THREAD

**Issue by qull** [xieziyu/ngx-echarts#121]
运行demo的时候报错：this._resize$.pipe is not a function，位置在NgxEchartsDirective.prototype.onOptionsChange这个方法里

**Comment by xieziyu** [comment]
@qull 
你用代码的是master branch上的吗?

**Comment by qull** [comment]
@xieziyu 
"rxjs": "5.2.0"

**Comment by xieziyu** [comment]
@qull 
OK，我会发布一个更新兼容这个版本

**Comment by xieziyu** [comment]
@qull 
请更新到 2.3.1 试一下

**Comment by qull** [comment]
@xieziyu 
Thanks,问题解决了
