### ISSUE TITLE
TypeError: Cannot read property 'getType' of null

### ISSUE THREAD

**Issue by qq1209974887** [xieziyu/ngx-echarts#127]
能够正常获取echartsInstance实例，但在生成Base64位格式的图片调用其getDataURL方法时报错，不知道什么原因？截图：
![image](https://user-images.githubusercontent.com/18743063/43705004-f8be036a-9993-11e8-9e5a-2801b00744af.png)
![image](https://user-images.githubusercontent.com/18743063/43705031-0d897f5e-9994-11e8-9abc-05a760ad4337.png)
![image](https://user-images.githubusercontent.com/18743063/43705169-64110da6-9994-11e8-9423-520f10088b2e.png)

**Comment by qq1209974887** [comment]
后又测试该实例下的getDom方法，却是非常正常的，完全没问题，不知道是我哪里使用错误了。

**Comment by HowToMeetYou** [comment]
在echart的finish事件中调取应该不会报错

**Comment by qq1209974887** [comment]
1
