### ISSUE TITLE
我如果想饼状图和柱状图的颜色渐变，应该怎么做

### ISSUE THREAD

**Issue by AntoniaQiao** [xieziyu/ngx-echarts#13]
![image](https://user-images.githubusercontent.com/19327642/28108210-5608feda-671d-11e7-91eb-737035a71888.png)
![image](https://user-images.githubusercontent.com/19327642/28108231-651cb6b4-671d-11e7-8595-00620df34f83.png)

**Comment by xieziyu** [comment]
@AntoniaQiao 请查看echarts的官方文档中pie图配置项中的lineStyle属性。
http://echarts.baidu.com/option.html
