### ISSUE TITLE
unwanted change detection

### ISSUE THREAD

**Issue by smnbbrv** [xieziyu/ngx-echarts#132]
Hi @xieziyu 

just started to play around the lib and found out that the following lines trigger unwanted change detection:

https://github.com/xieziyu/ngx-echarts/blob/03c817b9c513b35a477101eb1863005ce51e0d3e/projects/ngx-echarts/src/lib/ngx-echarts.directive.ts#L144

This could lead to poor performance on big pages especially events like mousemove. 

What do you think of a feature that allows to disable `this._ngZone.run` and delegate taking care of change detection to the end user?

Something like `detectEventChanges` which is `true` by default?

**Comment by xieziyu** [comment]
@smnbbrv 
It makes sense to me. It will be included in the next release. Thanks.

**Comment by xieziyu** [comment]
Published in v4.0.0-beta.1

**Comment by smnbbrv** [comment]
super!

This is actually sad that there is no way to deal with those eventEmitter things...

I created a [stackoverflow question](https://stackoverflow.com/q/51787972/1990451), who knows, maybe there is a better solution to the problem.

**Comment by smnbbrv** [comment]
Look at the [answer](https://stackoverflow.com/a/51788839/1990451). Not that beautiful but still can be useful some day ;)
