### ISSUE TITLE
Provide a way to "dynamically" change the theme of an echarts chart

### ISSUE THREAD

**Issue by ciukstar** [xieziyu/ngx-echarts#133]
I know that there are some work-around ways to this issue, but can you select the best one and implement it as something like <div echarts [(dynaTheme)]="myTheme">. The scenario is to "synchronize" angular's light/dark theme with echarts' light/dark theme at runtime.
It's somehow annoying that echarts lacks this "change dynamically the theme" :)
Thanks!

**Comment by xieziyu** [comment]
@ciukstar 
No problem, I will try to find a way.

**Comment by xieziyu** [comment]
@ciukstar 
This feature is supported in v4.0.0-beta.1

**Comment by ciukstar** [comment]
Tested. It works as expected. Thank you for your really quick reply!

**Comment by ciukstar** [comment]
Applied the new [theme] to all charts (20+) in my projects. Works very well. Just want to thank you! You really saved my day!
