### ISSUE TITLE
Error: Component series.bar3D not exists. Load it first

### ISSUE THREAD

**Issue by mehdishahdoost** [xieziyu/ngx-echarts#139]
Hi all, I use echart's 3DBar on my project but i get this error:
 Error: Component series.bar3D not exists. Load it first
any suggestion?

**Comment by xieziyu** [comment]
@mehdishahdoost 
You need to install ECharts GL first and then import it in your project. I will update README later. Thanks for reporting this issue.

1. `npm install echarts-gl --save`
2. Add the following in your `tsconfig.json`:
```diff
"paths": {
    "echarts": [
        "node_modules/echarts/dist/echarts.min.js"
    ],
+   "echarts-gl": [
+       "node_modules/echarts-gl/dist/echarts-gl.min.js"
+   ]
}
```
3. Add the following in your `main.ts`:
```typescript
import 'echarts-gl';
```

**Comment by mehdishahdoost** [comment]
thanks.my issue solved.
