### ISSUE TITLE
我在一个cli的项目里面安装环境问题

### ISSUE THREAD

**Issue by shao37142** [xieziyu/ngx-echarts#14]
我在一个cli的项目里面执行
npm install echarts --save
npm install ngx-echarts --save
之后就出现好几个类似这种的错误
ERROR in ./~/jquery/lib/node-jquery.js
Module not found: Error: Can't resolve 'xmlhttprequest' in 'F:\test\lite-version\node_modules\jquery\lib'
 @ ./~/jquery/lib/node-jquery.js 8:28-53
 @ ./src/lib.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4321 ./src/main.ts,
请教一下如何解决...

**Comment by xieziyu** [comment]
@shao37142 请检查一下你的工程配置。echarts和ngx-echarts并不依赖jquery插件。

**Comment by shao37142** [comment]
@xieziyu 谢谢回答,但是我在安装之前是ok的,安装之后就出现了这个问题...可否提示我一下解决思路...

**Comment by xieziyu** [comment]
@shao37142 从你的错误信息，我只能理解是其他某个插件引起的问题，我很好奇echarts和ngx-echarts为何会对此产生影响。如果你方便的话，可以把代码库发出来我看一下

**Comment by shao37142** [comment]
@xieziyu 好的,能否提供一个邮箱...

**Comment by xieziyu** [comment]
@shao37142 ziyu.xie@foxmail.com
