### ISSUE TITLE
Slow automatically resize on show/hide sidebar (CoreUI)

### ISSUE THREAD

**Issue by dolgovnv** [xieziyu/ngx-echarts#141]
When I run the [demo](https://xieziyu.github.io/ngx-echarts/#/usage/basic) and change the size of the browser window - the chart automatically resize quite quickly.
However, when I hide or show the sidebar, the chart automatically resize very slowly (10-15 seconds).
Screenshots:
![2018-09-21 13-49-03](https://user-images.githubusercontent.com/9606505/45861217-54385980-bda6-11e8-8795-defdc6a39f84.png)
![2018-09-21 13-49-17](https://user-images.githubusercontent.com/9606505/45861222-5b5f6780-bda6-11e8-8f00-1dfeca1031fc.png)

Can you tell me how to speed up the automatically resize?

**Comment by xieziyu** [comment]
@dolgovnv 
One way is to manually trigger angular change detection on the page component when sidebar is toggled
