### ISSUE TITLE
Hi I have upgraded to Angular 6 and Rxjs 6 and I am now getting this error when using ngx-excharts

### ISSUE THREAD

**Issue by shaneamondos** [xieziyu/ngx-echarts#142]
rxjs_Observable__WEBPACK_IMPORTED_MODULE_1__.Observable.of is not a function
    at ChangeFilter.push../node_modules/ngx-echarts/ngx-echarts.es5.js.ChangeFilter.notEmpty (ngx-echarts.es5.js:30)
    at NgxEchartsDirective.push../node_modules/ngx-echarts/ngx-echarts.es5.js.NgxEchartsDirective.ngOnChanges (ngx-echarts.es5.js:113)
    at checkAndUpdateDirectiveInline (core.js:9239)
    at checkAndUpdateNodeInline (core.js:10507)
    at checkAndUpdateNode (core.js:10469)
    at debugCheckAndUpdateNode (core.js:11102)
    at debugCheckDirectivesFn (core.js:11062)
    at Object.eval [as updateDirectives] (DataDonutComponent.html:2)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:11054)
    at checkAndUpdateView (core.js:10451)

**Comment by gunpal5** [comment]
I have same issue.

**Comment by shaneamondos** [comment]
Any chance we can get an update on whether this will be looked at? I have re-tried the upgrade and the issue still persists. If this is blocking me for much longer then I will have to change.

**Comment by shaneamondos** [comment]
ngx-echarts: 2.3.1
echarts: 4.1.0
@types/echarts: 4.1.1

Sorry I've only just noticed that ngx-echarts wasn't the most recent one. I was looking at the echarts version.

I have now downloaded 4.0.0 for ngx-echarts but I now get a different error on build and found that someone already raised this issue #143. The solution for him was to set the baseUrl in his tsconfig file but this is already set in mine and I am still getting this issue.

**Comment by xieziyu** [comment]
@shaneamondos 
1. Did you remove echarts script in angular.json?
2. What's the `baseUrl` in your tsconfig.json?
3. What's the `path` for echarts in your tsconfig.json?

**Comment by shaneamondos** [comment]
1. Yes
2. "baseUrl": "./",
3. "echarts": [
        "node_modules/echarts/dist/echarts.min.js"
      ]

**Comment by MatiasChao** [comment]
Hello, i have the same problem.

ngx-echarts: 2.3.1
echarts: 4.2.0

- I remove the script in angular.json
- I haven't the properties baseUrl and echarts in the file tsconfig.json
tsconfig.json
{
	"compilerOptions": {
		"outDir": "./dist/",
		"module": "commonjs",
		"target": "es5",
		"moduleResolution": "node",
		"sourceMap": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"lib": [
			"es7",
			"dom"
		],
		"noImplicitAny": false,
		"typeRoots": [
			"node_modules/@types/"
		],
		"suppressImplicitAnyIndexErrors": true,
		"allowJs": true,
		"allowSyntheticDefaultImports": true,
		"alwaysStrict": true
	}
}

Note: I add the correct address (echart in tsconfig.json) but it says it's wrong (the direction). 

Any ideas? Thanks
