### ISSUE TITLE
Series Type Custom - access data source in calling component

### ISSUE THREAD

**Issue by lbe** [xieziyu/ngx-echarts#166]
NOTE:  **This problem is solved by implementing the renderItem callback as a closure and lexically defining a copy of the data needed needed within the renderItem function within the closure** lbe - 2019/01/18

I apologize in advance if I am missing something in newness to Angular.

I am using eCharts to draw a diagram much as you would on HTML5 Canvas.  My reason for using eCharts is that is result needs to be scaled with other line charts that appear in the same frame.

I have created working model in pure javascript in the REPL  on the eCharts demo site.  It is based off the demo chart "[Custom Cartesian Polygon](https://ecomfe.github.io/echarts-examples/public/editor.html?c=custom-cartesian-polygon)".  As in the example, I define a variable data using `var data = []`.  In the REPL, the variable data is global and is accessible in the for loop beginning on line 19.

I have built out an angular app.component.ts that attempts to match my javascript version.  In it, everything works fine until eCharts calls the `renderItem` callback.  Since the process is outside of the scope of app.component, it cannot see my custom data.  Is there a pattern in ngx-echarts and/or angular that I should be using to handle this?

FYI, I am familiar with the more out of the box option of using `api.value(n)` to access data values.  This only works for numeric values.  My data element is an Object that I parse to create a polygon graphic.

Thanks in advance for your help!

lbe

**Comment by lbe** [comment]
@xieziyu 
I gave the service a try but ran into the same scoping problem.

I tried using the following closure pattern but experienced the opposite result where the `echarts.*` namespace was not within the closure scope.

```
createRenderItem() {
    const d = this.d; //this.d is where my data exists
    const echarts = this.echarts;
    return function (params, api) {
      const dCur = d.renderData[params.seriesId][params.dataIndex];
      return {
        ...
        shape: {
           points: echarts.graphic.clipPointsByRect(completeset, {
             x: params.coordSys.x,
             y: params.coordSys.y,
            width: params.coordSys.width,
            height: params.coordSys.height
         })
      },
      ...
  }
}

public loadChart() {
  const rederItem = this.createRenderItem();
  this.options = {
    ...
    series: [
      ...
      {
        name: 'Earth Model',
        id: 'EarthModel',
        data: this.d.renderData.EarthModel,
        type: 'custom',
        renderItem: renderItem
      },
      ...
  }
}   
```

With this pattern, execution halts with the following error.
![screen shot 2019-01-17 at 5 31 49 pm](https://user-images.githubusercontent.com/1119377/51355808-d64b3d00-1a7d-11e9-94e2-90be7c0e613b.png)
'graphic' in this case is a child of echarts `echarts.graphic.clibPointsByRect`

If I remove the call errored above, the renderItem executes successfully, but I get a canvas drawing error in when echarts is trying to draw on the cas.  The following picture is a screenshot showing the console.log return value from the renderItem function and the error that I received.

![screen shot 2019-01-17 at 5 22 26 pm](https://user-images.githubusercontent.com/1119377/51355514-0cd48800-1a7d-11e9-89c9-3120f07e0769.png)

I cannot share my specific code and data since it is the property of one of my customers.  I will create a sample in javascript for use in the eCharts demo REPL and will create an Angular version that recreates my errors as soon as I can.  I am too inexperienced with Angular to truly understand the issue here.  But, it seems to me to either be an intended effect of data isolation within Angular or an unintended side effect of how ngx-echarts wraps angular.  If it is the former, then I have to live with it.  If the latter, then I hope we can address.

I am also looking at how to transform the input data into a form that doesn't need external data access and only depends on the `api.value()` function to get data. I can probably get this to work, but it will take a lot more code to accomplish and likely will not be as performant.

Thanks for your response and assistance.

lbe

**Comment by lbe** [comment]
@xieziyu 
I gave the service a try but ran into the same scoping problem.

I was to get around the scope problem by creating an enclosure.

``` typescript
createRenderItem() { // function to create the closure
    const d = this.d; //this.d is where my data exists
    const echarts = this.echarts;
    return function (params, api) {
      const dCur = d.renderData[params.seriesId][params.dataIndex];
      return {
        type: 'polygon',
        ...
        shape: {
           points: completeset
         }
      },
      ...
  }
}

public loadChart() {
  const rederItem = this.createRenderItem(); // the closure
  this.options = {
    ...
    series: [
      ...
      {
        name: 'Earth Model',
        id: 'EarthModel',
        data: this.d.renderData.EarthModel,
        type: 'custom',
        renderItem: renderItem // the closure in use
      },
      ...
  }
}   
```

Unfortunately, if I try to call `echarts.graphic.clipPointsByRect` in the shape definition, I receive the following error
![screen shot 2019-01-17 at 5 31 49 pm](https://user-images.githubusercontent.com/1119377/51355808-d64b3d00-1a7d-11e9-94e2-90be7c0e613b.png)
It appears that I now lose access to the `echarts.*` since I either can not or do not know how to do this.

I cannot share my specific project code and data since it is the property of one of my customers.  I have created a [gist](https://gist.github.com/lbe/4812efee0bc650383be665714a194416) with representative Angular code that produces the same result as my project code.  To use this [gist](https://gist.github.com/lbe/4812efee0bc650383be665714a194416), start with [ngx-echarts-starter](https://github.com/search?q=ngx-echarts-starter).  Add exampleData1.json to the assets directory.  Replace the app.component html and ts files in ngx-echarts-starter and you should be able to get a succesful chart.

To get the error result, change the true to false at line 49 of the app.component.ts file.

Overall this approach should work, unless one needs to clip because of the use of DataZoom.  In that case, they will need to write their own clipping function since `echarts.*` cannot be accessed.

Is there a way to preserve the access to `echarts.*`?

Is there a change that can be made to ngx-echarts to support the renderItem callback without needing to use a closure?

Thanks again for your response and assistance.

lbe

**Comment by xieziyu** [comment]
@lbe 
You should not access `echarts.*`. Instead, you can import them from echarts.
```
import { EChartOption, graphic } from 'echarts';
```

And then use `graphic.clipPointsByRect` directly in your methods.

**Comment by lbe** [comment]
@xieziyu

Thanks for the information on changing my import.  To my current degree of testing, everything appears to work properly.

Thanks for your guidance!!

lbe
