### ISSUE TITLE
Echarts Custom Build 自定义构建 Echarts

### ISSUE THREAD

**Issue by zinsserzh** [xieziyu/ngx-echarts#167]
I am wondering how likely ngx-echarts can support custom build. I am quite new to js/ts/angular so feel free to correct me if anything is wrong.

I believe the entire echarts package is included for webpack building due to this line from [`ngx-echarts.directive.ts`](https://github.com/xieziyu/ngx-echarts/blob/5706b424070598ec1ddb236d267fcdfc5e0d3620/projects/ngx-echarts/src/lib/ngx-echarts.directive.ts#L2)

```
import { EChartOption, ECharts, init } from 'echarts';
```

Because sideEffect is not set (and it shouldn't) in echarts package, a single import from echarts causes the entire package to be included during webpack building. Since echarts has well documented method for webpack custom build, I think it make sense for ngx-echarts to support it as well. For my own project, 70% of the vendor chunk is echarts. However, most of the features included are not used for my project.

I propose the following method to add such support:

1. Modify the line mentioned above to import directly from echarts' core module `lib/echarts` (not sure if is possible and how to do that)
2. Add `import * as echarts from 'echarts'` and change the NgModule imports of `NgxEchartsModule` somehow so that the entire echarts is included for build when `NgxEchartsModule` is imported. This ensures that the current behavior is not changed.
3. Create a new module `NgxEchartsBareModule` just like `NgxEchartsModule` but does not trigger the entire echarts package to be included.
4. Provide an extra template ts file `NgxEchartsCustomBuildModule` that can be copied to one's angular project. Developers are in charge of selecting echarts modules by commenting lines for echarts modules that are not needed and import this module to the app.module so that required files are included in the webpack build properly. Something like this:

```
import * from 'echarts/lib/chart/line';
import * from 'echarts/lib/chart/bar';
// import * from 'echarts/lib/chart/scatter';
// import * from 'echarts/lib/chart/radar';
...
```

So, the normal flow and the existing documentation are not changed. The entire echarts is still going to be included in the webpack build. If one wants to squeeze some loading budget, he or she can:

1. Change `NgxEchartsModule` to `NgxEchartsBareModule`.
2. Copy `NgxEchartsCustomBuildModule` from the npm package/github blob/documentation to the angular project.
3. Comment out the lines that are not needed.
4. Import `NgxEchartsCustomBuildModule` to `AppModule`.

-----

我想知道 ngx-echarts 是否可以支持自定义构建。我刚刚开始接触 js/ts/angular 所以如果有说的不对的地方欢迎指正~

目前在编译的过程中因为下面这行来自 [`ngx-echarts.directive.ts`](https://github.com/xieziyu/ngx-echarts/blob/5706b424070598ec1ddb236d267fcdfc5e0d3620/projects/ngx-echarts/src/lib/ngx-echarts.directive.ts#L2) 的代码，整个echarts的包都被加入在webpack封装中：

```
import { EChartOption, ECharts, init } from 'echarts';
```

因为 echarts 的包中并没有设置 sideEffect （也并不应该被设置）虽然没有 import 所有东西，但是整个 echarts 包还是会被加到 webpack 的封装中。Echarts 官方有详细的使用 webpack 自定义构建的文档，外加完整的 Echarts 占用体积比较大，很多不需要的功能其实可以删除，所以我觉得理想情况是 ngx-echarts 也能支持自定义构建

我提个参考方案：

1. 把上边提到的那行代码改成从 echarts 的核心模块 `lib/echarts` 中直接 import （不是很清楚是否能实现以及怎么实现）
2. 在 `NgxEchartsModule` 中加入 `import * as echarts from 'echarts'` 并更改其 `NgModule` 的 `imports` 。这样 `NgxEchartsModule` 可以触发整个 echarts 被加入到 webpack 的封装中，保证了现有行为不被改变
3. 加入一个新的模块 `NgxEchartsBareModule` ，与 `NgxEchartsModule` 相似，但是不会触发整个echarts被封装
4. 额外给开发者提供一个ts模板 `NgxEchartsCustomBuildModule` 。开发者可以把这个文件加入到自己的angular项目中，并通过注释的方法选择需要的echarts模块，类似于下面这样的：

```
import * from 'echarts/lib/chart/line';
import * from 'echarts/lib/chart/bar';
// import * from 'echarts/lib/chart/scatter';
// import * from 'echarts/lib/chart/radar';
...
```

这样原本的使用 `NgxEchartsModule` 没有发生改变，现有的文档也不需要做出额外改动。如果开发者想要使用自定义构建：

1. 更换 `NgxEchartsModule` 为 `NgxEchartsBareModule`
2. 从npm package/github blob/文档把 `NgxEchartsCustomBuildModule` 复制到自己的angular项目中
3. 把不需要的模块注释掉
4. 在 `AppModule` 中引用 `NgxEchartsCustomBuildModule`

**Comment by xieziyu** [comment]
@zinsserzh 
确实是一个比较有趣的想法。按需打包很有意义，可以考虑在未来的版本中加以支持

**Comment by Ludevik** [comment]
I would like to see support for custom build too. 

Currently to have custom build one has to build custom `echarts` either with [online build tool](https://echarts.apache.org/builder.html) or with the [build script](https://echarts.apache.org/tutorial.html#Create%20Custom%20Build%20of%20ECharts) and put the minified version into the project somewhere. Next step is to add `echarts` to `tsconfig.json`:
```
{
  ...
  "compilerOptions": {
    ...,
    "paths": {
      ...,
      "echarts": ["lib/echarts.custom.min.js"]
    }
  }
}
```

so that every `import {something} form 'echarts'` takes the imported stuff from the custom build instead of `node_modules/echarts`.

**Comment by AIxiuxiu** [comment]
我也有这需求，暂时解决办法直接修改echarts的index.js,将不需要的模块注释掉
![](https://raw.githubusercontent.com/AIxiuxiu/readme_add_pic/master/echarts.png)

还有问题我在angular中使用时，打包会把echarts打包在主文件main.js 中，使主文件太大了，不知道如何才能提出来单独打包为一个chunk文件

**Comment by zinsserzh** [comment]
@AIxiuxiu 
> 还有问题我在angular中使用时，打包会把echarts打包在主文件main.js 中，使主文件太大了，不知道如何才能提出来单独打包为一个chunk文件

在 `angular.json` 中添加/设置 `vendorChunk` 为 `true` 或者在 `ng build` 的时候添加 flag
```bash
ng build --vendorChunk=true
```
详见 [`angular.json`](https://angular.io/guide/workspace-config#additional-build-and-test-options) 和 [`ng build`](https://angular.io/cli/build#options) 官网的文档

**Comment by xieziyu** [comment]
This feature is supported in v4.2.0. Please refer to:
https://github.com/xieziyu/ngx-echarts#custom-build
