### ISSUE TITLE
option发生变化的时候，图表不重绘。

### ISSUE THREAD

**Issue by akeyz** [xieziyu/ngx-echarts#17]
这个是bug，还是本身就没有这个功能？

谢谢！

**Comment by xieziyu** [comment]
@akeyz 
这个不是bug，并且这个功能也存在。你的图表之所以没有重绘，是因为你只是改变了option的属性值，而没有改变option对象本身的引用。因此angular的change detection不会调用ngOnChanges的钩子。

ngx-echarts从性能方面做了考量，所以也不会去用ngDoCheck做深度脏检查。所以，如果你想要改变option的属性值，同时使得图表重绘，那么最简单的方式是，改变一下option对象的引用，例如：
```javascript
this.myOption = Object.assign({}, this.myOption);
```

**Comment by akeyz** [comment]
好的，多谢！
