### ISSUE TITLE
用echarts指令构建图表时候，默认高度设置为了400px

### ISSUE THREAD

**Issue by vistwang** [xieziyu/ngx-echarts#187]
![997D7BD0-7F44-4659-AE93-5CE1D071FA79](https://user-images.githubusercontent.com/35866874/57519985-2ad93780-734f-11e9-9333-ff015d91eb28.png)

**Comment by xieziyu** [comment]
@vistwang 
echarts需要容器有固定高宽才能工作，如果你没有设置高度，就会给默认的400px，这是一个feature

**Comment by vistwang** [comment]
> @vistwang
> echarts需要容器有固定高宽才能工作，如果你没有设置高度，就会给默认的400px，这是一个feature

好的，感谢你的回复，我了解下怎么配置自动高度
