### ISSUE TITLE
echartInstance missing connect() method

### ISSUE THREAD

**Issue by Pankesh88** [xieziyu/ngx-echarts#188]
As per this example: https://echarts.baidu.com/echarts2/doc/example/mix8.html#-en

there is a connect method for echart instance.

My main requirement is to be able to connect two charts and use them together just like the example link.

**Comment by xieziyu** [comment]
@Pankesh88 
The method is supported. I added a demo for you, please take a look at:
https://xieziyu.github.io/ngx-echarts/#/demo/advanced/connect-charts

**Comment by Pankesh88** [comment]
@xieziyu,

Thank you so much for such a quick turn-around. I really appreciate it. 

I tested the connect code with ngx-echarts version 4.1.1 and it worked, but my whole application in angular version 5, due to which I'm using ngx-echarts 2.3.1 version as recommended on the NPM page.

And the connect method is not working fine with 2.3.1

This is the error I'm getting in the console.

ERROR TypeError: Cannot read property 'group' of undefined
    at eval (echarts.js:1832)
    at Array.forEach (<anonymous>)
    at each (util.js:298)
    at Object.connect (echarts.js:1831)
    at DeviceRxPowerEchartsComponent.onChartInit2 (device-rx-power-echarts.component.ts:127)
    at Object.eval [as handleEvent] (DeviceRxPowerEchartsComponent.ngfactory.js:33)
    at Object.handleEvent (core.js:13589)
    at Object.handleEvent (core.js:14321)
    at dispatchEvent (core.js:10004)
    at eval (core.js:12343)

Can you please share an example where we can see the charts connect work with 2.3.1 version of ngx-echarts.

Thank you in advance!

**Comment by xieziyu** [comment]
@Pankesh88 
If you use v2.3.1, you can use `NgxEchartsService` which is an `echarts` wrapper. Here is a demo:

```ts
import { NgxEchartsService } from 'ngx-echarts';

//...
export class DemoComponent implements AfterViewInit {

  constructor(private nes: NgxEchartsService) { }

  ngAfterViewInit() {
    setTimeout(() => {
      const echarts = this.nes.echarts;
      const chartElement1 = document.getElementById('chart1');
      const chartElement2 = document.getElementById('chart2');
      const chart1 = echarts.getInstanceByDom(chartElement1);
      const chart2 = echarts.getInstanceByDom(chartElement2);
      echarts.connect([chart1, chart2]);
    });
  }

}
```

**Comment by Pankesh88** [comment]
Thank you so much it works!
