### ISSUE TITLE
通过npm 安装的包引入module问题

### ISSUE THREAD

**Issue by screamleen** [xieziyu/ngx-echarts#19]
1.2.3版本安装的包下有index.ts 和 index.js ，typescript 下引入的是index.ts ,这个文件没有封装ng 的module。

**Comment by xieziyu** [comment]
@screamleen 应该不存在你说的问题，安装包下是index.d.ts，这个typescript是不会引错的。

**Comment by screamleen** [comment]
import { AngularEchartsModule } from 'ngx-echarts/index.d';
这么引是不行的，会报错。
import { AngularEchartsModule } from 'ngx-echarts/index.js';
这样就可以。

**Comment by xieziyu** [comment]
@screamleen 你import的时候，不需要写index的，typescript会自动resovle；
正确的写法：
`import { AngularEchartsModule } from 'ngx-echarts';`
