### ISSUE TITLE
echarts.util.map equivalent.

### ISSUE THREAD

**Issue by kedomonzter** [xieziyu/ngx-echarts#199]
I'm trying to replicate the chart below in Angular but it seems some libs aren't available.
[this chart]https://gallery.echartsjs.com/editor.html?c=xBy7SAVcpx
especially this one.
return echarts.util.map(['time', 'cpu', 'memory', 'frame'], function (seriesName) {

**Comment by xieziyu** [comment]
@kedomonzter 
`.util` is exported by `echarts` but missing in `@types/echarts`. You just need to create an external type declaration file by yourself. Then add it to `compilerOptions / types` field of `tsconfig.json`.
```ts
// types.d.ts
declare namespace echarts {
  const util: any;
}
```

**Comment by mehmetific** [comment]
Thanks for the tip. 
Can we  create the demo below by using this util? 

https://echarts.apache.org/examples/en/editor.html?c=line-draggable

With the type defined and imported in tsconfig, it shows an error of :
ERROR ReferenceError: echarts is not defined

**Comment by ChristopherJBarr** [comment]
Or:

`(echarts as any).util.map();`
