### ISSUE TITLE
手动改变下x，y轴的值，图表不跟着变化

### ISSUE THREAD

**Issue by AntoniaQiao** [xieziyu/ngx-echarts#20]
setInterval(() => {
      this.i = this.i + 1;
      this.season.shift();
      this.season.push(this.getSeason()[this.i]);
      this.count.shift();
      this.count.push(this.getCount()[this.i]);
      this.increase.shift();
      this.increase.push(this.getIncrease()[this.i]);
      this.option.xAxis[0].data = this.season.slice();
      this.option.series[0].data = this.count.slice();
      this.option.series[1].data = this.increase.slice();
    }, 5000);

**Comment by xieziyu** [comment]
@AntoniaQiao 请参考[https://github.com/xieziyu/ngx-echarts/issues/17](https://github.com/xieziyu/ngx-echarts/issues/17)
