### ISSUE TITLE
Getting the value of the Marker point on datazoom event.

### ISSUE THREAD

**Issue by kedomonzter** [xieziyu/ngx-echarts#200]
I tried to attach this in the <div echarts (chartDataZoom)="onChartChange($event, 'chartDataZoom')" ...></div>
(chartDataZoom)="onChartChange($event, 'chartDataZoom')" I cannot get the value provided by the Markerdata point. How can I get its value?[](url)
![Screenshot 2019-07-08 at 10 00 02 PM](https://user-images.githubusercontent.com/1046316/60838775-ccec9300-a1cb-11e9-8c60-00b7e6224429.png)

**Comment by xieziyu** [comment]
@kedomonzter 
Sorry, I don't know if echarts exposed any API to get that computed value. Maybe you can ask echarts team for help.
https://github.com/apache/incubator-echarts/issues

**Comment by kedomonzter** [comment]
Thanks @xieziyu I got the date from here.
```
formatter: function(params) {  
}
```
