### ISSUE TITLE
'x' property doesn't exist in EChartTitleOption

### ISSUE THREAD

**Issue by djabif** [xieziyu/ngx-echarts#202]
Hi, thanks for this lib! I was trying [this example](https://echarts.apache.org/examples/en/editor.html?c=pie-legend) with your library and noted that the `title.x` property isn't available in `EChartTitleOption`. I did't find any other property that works properly for centering the title. What am I missing?  Thanks.

**Comment by xieziyu** [comment]
@djabif 
I think `left: 'center'` should work.

**Comment by djabif** [comment]
thanks!
