### ISSUE TITLE
ngx-echarts is not rendering correctly on brave browser

### ISSUE THREAD

**Issue by jorgemota** [xieziyu/ngx-echarts#210]
Hi, I was using ngx-echarts and angular 8: this versions:
"ngx-echarts": "^4.2.1",
"echarts": "^4.2.0-rc.1",
  "@angular/animations": "8.2.2",
    "@angular/common": "8.2.2",
    "@angular/compiler": "8.2.2",
    "@angular/core": "^8.2.5",
    "@angular/forms": "8.2.2",
    "@angular/platform-browser": "8.2.2",
    "@angular/platform-browser-dynamic": "8.2.2",
    "@angular/router": "8.2.2",
 "bootstrap": "^4.3.1",

If I run with ng serve I got the graph correctly
The code is 
html:
```
<div class="col-lg-12 col-md-12">
					<div class="card mb-4">
						<div class="card-body mb-5">
							<div class="card-title">Actividad últimos 15 días</div>
							<div echarts [options]="salesChartBar" [autoResize]="true" style="height: 300px;"></div>
						</div>
					</div>
				</div>
```
ts:
```
salesChartBar: EChartOption;
ngOnInit() {
 items = [{ 'id': 20190910, 'correct': 364, 'fail': 230, 'dataLabel': '10-09' },
            { 'id': 20190911, 'correct': 2210, 'fail': 730, 'dataLabel': '11-09' },
            { 'id': 20190912, 'correct': 2867, 'fail': 966, 'dataLabel': '12-09' }]
            const correct: number[] = [];
            const fail: number[] = [];
            const labels: string[] = [];
            for (const item of items) {
                correct.push(item.correct);
                fail.push(item.fail);
                labels.push(item.dataLabel);
            }
const maxCorrect = Math.max.apply(Math, correct.map(function (o) { return o; }));
            const maxFail = Math.max.apply(Math, fail.map(function (o) { return o; }));
            const interval = Math.round((maxCorrect > maxFail ? maxCorrect : maxFail) / 10);
            console.log(interval);
            this.salesChartBar = {
                legend: {
                    borderRadius: 0,
                    orient: 'horizontal',
                    x: 'left',
                    data: ['Correctos', 'Errores']
                },
                grid: {
                    left: '8px',
                    right: '8px',
                    bottom: '20px',
                    containLabel: true
                },
                tooltip: {
                    show: true,
                    backgroundColor: 'rgba(0, 0, 0, .8)'
                },
                xAxis: [{
                    type: 'category',
                    data: labels,
                    axisTick: {
                        alignWithLabel: true
                    },
                    splitLine: {
                        show: false
                    },
                    axisLine: {
                        show: true
                    }
                }],
                yAxis: [{
                    type: 'value',
                    min: 0,
                    max: maxCorrect > maxFail ? maxCorrect : maxFail,
                    interval: interval,
                    axisLine: {
                        show: false
                    },
                    splitLine: {
                        show: true,
                        interval: 'auto'
                    }
                }],
                series: [{
                    name: 'Correctos',
                    data: correct,
                    label: { show: false, color: '#0168c1' },
                    type: 'bar',
                    barGap: 0,
                    color: '#7569b3',
                    smooth: true,
                },
                {
                    name: 'Errores',
                    data: fail,
                    label: { show: false, color: '#639' },
                    type: 'bar',
                    color: '#bcbbdd',
                    smooth: true
                }]
            };
        });
}
```
with this fixed data, running in brave (ng serve) I got this:
![image](https://user-images.githubusercontent.com/1952329/64837110-30b78180-d5aa-11e9-92c2-ebe883533cb5.png)

The same but compiled with --prod and served from payara:
![image](https://user-images.githubusercontent.com/1952329/64837256-c6eba780-d5aa-11e9-88a1-247ac776594e.png)

I tought my Brave browser (Version 0.71.72 Chromium: 76.0.3809.132 (Official Build) unknown (64-bit))  was damaged, but tried in 3 different computers and got the same result only with brave. If I open the same page in production or ng serve in firefox, chrome or edge I  don't get this behavior, only with brave browser. No warnings and no errors on console on both cases.

**Comment by xieziyu** [comment]
@jorgemota 
I think it's an echarts issue on brave browser. You can try to use pure [echarts API](https://www.echartsjs.com/en/api.html#echartsInstance.setOption) `.setOption()` without ngx-echarts. If you still meet the same problem, you can open an issue on https://github.com/apache/incubator-echarts

**Comment by jorgemota** [comment]
> @jorgemota
> I think it's an echarts issue on brave browser. You can try to use pure [echarts API](https://www.echartsjs.com/en/api.html#echartsInstance.setOption) `.setOption()` without ngx-echarts. If you still meet the same problem, you can open an issue on https://github.com/apache/incubator-echarts

Thanks for the advice, In latest  version fixed the problem:

![image](https://user-images.githubusercontent.com/1952329/68266463-d0c2e180-0014-11ea-9a8e-dd9a46ea74c7.png)
