### ISSUE TITLE
After import chart by demand, package size seems to be as large as before

### ISSUE THREAD

**Issue by KerryXuanWang** [xieziyu/ngx-echarts#214]
Hello team,

As title described, i just import 'bar' and 'gauge' chart, and after build app, i use 'webpack-bundle-analyzer' to analyze the package size, echarts occupies a large part, almost 400KB after gzip.
Do you have any suggestions?

Thanks a lot & Look forward to your reply.

**Comment by xieziyu** [comment]
@KerryXuanWang 
Did you import `NgxEchartsCoreModule` or `NgxEchartsModule`?
Please refer to https://github.com/xieziyu/ngx-echarts#custom-build

**Comment by KerryXuanWang** [comment]
Yes, i do refer to the custom-build. And below is the import code.
import { NgxEchartsCoreModule } from 'ngx-echarts/core';
Any other possibilities? Thanks!

**Comment by xieziyu** [comment]
Do you have any file that imports echarts? Do you use theme file?

**Comment by KerryXuanWang** [comment]
Sorry, it's my bad. If not on demand import, the gzip size is over 1MB(too large).
Thanks for your time.
