### ISSUE TITLE
Does not work with IVY enabled

### ISSUE THREAD

**Issue by ottodranik** [xieziyu/ngx-echarts#217]
Getting an error during ivy-ngcc (latest 8.3.21) compile.

Firstly get a WARNING:
> Warning: Entry point 'ngx-echarts/core' contains deep imports into '/.../node_modules/echarts/lib/echarts'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
> Compiling @angular/animations : fesm

And then an error:

> Compiling ngx-echarts/core : fesm2015 as esm2015
> Compiling ngx-echarts/core : fesm5 as esm5
> Compiling ngx-echarts/core : esm2015 as esm2015
> Error: Unable to write a reference to NgxEchartsCoreDirective in /.../fe/node_modules/ngx-echarts/esm2015/core/lib/ngx-echarts-core.directive.js from /.../fe/node_modules/ngx-echarts/esm2015/core/lib/ngx-echarts-core.module.js
>     at ReferenceEmitter.emit (/.../fe/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:54:19)
>     at Object.toR3Reference (/.../fe/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:138:31)
>     at NgModuleDecoratorHandler._toR3Reference (/.../fe/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:287:31)
>     at /.../fe/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:131:83
>     at Array.map (<anonymous>)
>     at NgModuleDecoratorHandler.analyze (/.../fe/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:131:48)
>     at Object.analyzeDecorators (/.../fe/node_modules/@angular/compiler-cli/ngcc/src/analysis/util.js:73:34)
>     at DecorationAnalyzer.analyzeClass (/.../fe/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:126:27)
>     at /.../fe/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:120:55
> at Array.map (<anonymous>)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! fe@0.0.0 postinstall: `ivy-ngcc`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the fe@0.0.0 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Possible solution https://github.com/angular/angular/issues/29361#issuecomment-524503373

**Comment by Credo-Zhao** [comment]
This issue can be closed.
