### ISSUE TITLE
Angular9 support

### ISSUE THREAD

**Issue by hijamoya** [xieziyu/ngx-echarts#224]
Please upgrade to angular9
```
 Entry point 'ngx-echarts/core' contains deep imports into '/Users/jam/go/src/git.eng.lativ.com/eng/lativ/erp/frontend/node_modules/echarts/lib/echarts'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
```

**Comment by xieziyu** [comment]
@hijamoya 
It seems I need to rewrite the implementation of custom build. 😢 
I'm planning to rewrite the whole project to support angular 9. Thank you for your report.

**Comment by arthurflor23** [comment]
Hi, I'm using Angular 9.1 now and I didn't have this problem.
The module works fine here.

**Comment by ciukstar** [comment]
Same warning for me:
```Warning: Entry point 'ngx-echarts/core' contains deep imports into '<project_home>/node_modules/echarts/lib/echarts', '<project_home>/node_modules/echarts/dist/echarts.min.js'. This is probably not a problem, but may cause the compilation of entry points to be out of order.```

**Comment by msyesyan** [comment]
@xieziyu do you have a plan about when to finish the angular 9 support? ^_^

**Comment by xieziyu** [comment]
Please upgrade to `ngx-echarts` v5.0.0

**Comment by ciukstar** [comment]
> Please upgrade to `ngx-echarts` v5.0.0

Successfully updated to `ngx-echarts@5.0.0`. No more warnings. Many thanks.

**Comment by vishnu-dev** [comment]
Shouldn't this be closed @xieziyu? The warning disappears after upgrading.
