### ISSUE TITLE
ViewChild with NgxEchartsDirective

### ISSUE THREAD

**Issue by VeselAbaya** [xieziyu/ngx-echarts#226]
Hi! Thanks for that lib.

I've stuck with an issue
When I use NgxEchartsDirective in this way: 
`@ViewChildren(NgxEchartsDirective, {read: QueryList}) echart: QueryList<NgxEchartsDirective>`, error occured in the console
Module not found: Error: Can't resolve 'ngx-echarts/lib/ngx-echarts.directive' 

What can I do with that?

**Comment by xieziyu** [comment]
@VeselAbaya 
Sorry about that, `NgxEchartsDirective` is not exported from the top-level library. Maybe you could use the echartInstance object (emitted by `chartInit`) instead ? I will export this class in the next release.

**Comment by VeselAbaya** [comment]
Thank a lot for fast feedback! Yeah **chartInit** is a solution at the moment :)
