### ISSUE TITLE
Time error

### ISSUE THREAD

**Issue by Rimander** [xieziyu/ngx-echarts#227]
I create an array with a date and values.

`data.total.push([date.getTime(), input.total]);`
// Sat Feb 01 2020 00:00:00 GMT+0100 , 13135
`axisLabel: {
                        formatter: (function (value) {
                            let date = new Date(value);
                            console.log(date);
                            return date.getMonth() + 1 + "-" + date.getFullYear();
                        })
                    },`
print other date ( Feb 19 2020.... )

**Comment by xieziyu** [comment]
It seems not a bug of `ngx-echarts`
