### ISSUE TITLE
Options for minorTick, minorSplitLine missing

### ISSUE THREAD

**Issue by elnipa** [xieziyu/ngx-echarts#228]
Hi there,

in the charts documentation there are options for xAxis|Axis. minorTick and minorSplitLine which would be super helpful to use in ngx-echarts.
https://www.echartsjs.com/en/option.html#xAxis.minorTick
https://www.echartsjs.com/en/option.html#xAxis.minorSplitLine
However, those options seem not be part of the echarts options interface for CartesianAxis.

I wonder if you've have any plans to support this or how can I access those options as part of echarts?

Thanks in advance.

**Comment by xieziyu** [comment]
Please open issue in `@types/echarts` lib
