### ISSUE TITLE
xAxis 的minorTick、minorSplitLine等属性 ts无法识别

### ISSUE THREAD

**Issue by chanceliao** [xieziyu/ngx-echarts#229]
angular 版本7.3.9, @types/echarts@4.4.5
无法识别minorTick、minorSplitLine等属性 ,ts报错： error TS2322: Type '{ type: "value"; position: "top"; min: number; max: number; interval: number; splitLine: { lineStyle: { color: string[]; }; }; axisLine: { show: true; }; axisTick: { lineStyle: { color: string; }; }; axisLabel: { ...; }; minorTick: { ...; }; minorSplitLine: { ...; }; }' is not assignable to type 'XAxis | XAxis[]'.

调试时能看到效果，无法build

**Comment by xieziyu** [comment]
是 `@types/echarts` 库的问题
