### ISSUE TITLE
数据设置Option在切换的时候如果是空的话，好像图表就画不出来

### ISSUE THREAD

**Issue by sadydai** [xieziyu/ngx-echarts#23]
这个怎么销毁一个表？好像dispose不行。。。如果在切换option设置的时候，option = {}的话好像页面上的图表没有改变，还是切换前的设置。。。

**Comment by xieziyu** [comment]
@sadydai 直接销毁echarts指令所在的dom即可。

**Comment by sadydai** [comment]
嗯嗯
