### ISSUE TITLE
theme not working (macarons) Nightingale Rose chart

### ISSUE THREAD

**Issue by icojb25** [xieziyu/ngx-echarts#235]
Using cut and paste from Getting Started guide, for Rose diagrams seems to be broken? 

Setting:
theme: string = 'macarons'; or 'undefined' 

both seem to result in the default (undefined) theme being applied.

**Comment by xieziyu** [comment]
Did you import the theme file?

```
import * as echarts from 'echarts';

import 'echarts/theme/macarons.js';
```
