### ISSUE TITLE
Charts are not rendered after building(Blank divs)

### ISSUE THREAD

**Issue by adisreyaj** [xieziyu/ngx-echarts#237]
When serving the application the charts are rendered properly without any issues. But when production build is done (`ng build --prod) and we run the application the charts are not being rendered all the divs are just empty.

Configuration:
- Angular v 8.2.14
- ngx-echarts v5.0.0 
- echarts v4.7.0

When I try building without `prod` flag, the charts are working fine. I suppose it has do something with the AOT compilation.

**Comment by xieziyu** [comment]
@adisreyaj 
Maybe you can try this work-around:

```ts
import { init } from 'echarts';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NgxEchartsModule.forRoot({
      echarts: {
        init,
      },
    })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by adisreyaj** [comment]
This actually worked. 
So basically it has something to do with the module resolution when using the `import * as echarts from 'echarts'` style...right?

**Comment by lundmikkel** [comment]
I don't think this issue should have been closed. The workaround is not a proper solution, it's a ... workaround.
