### ISSUE TITLE
can't find the data values in echart click on scatter type.

### ISSUE THREAD

**Issue by KunalChhetri14** [xieziyu/ngx-echarts#238]
//Html
<div echarts [options]="chartOptions" (chartClick)="onChartClick($event)"

//.ts file
onChartClick(params){
      console.log("The params are : ", params);
}

//Output
![image](https://user-images.githubusercontent.com/31813752/82801271-afcfba00-9e9a-11ea-94fd-48867466c7ac.png)

I want the data points information.

**Comment by xieziyu** [comment]
@KunalChhetri14 
Did you bind `onChartClick` to `(chartClick)`?
