### ISSUE TITLE
Chart data update

### ISSUE THREAD

**Issue by parvezshah** [xieziyu/ngx-echarts#239]
Hi, Is there any example i can use to learn how to update chart data using API call or modify chart options on runtime

**Comment by xieziyu** [comment]
@parvezshah 
You can use `[merge]` in template, or you can use native echarts API: `chart.setOption()` that `chart` is emitted by `(chartInit)`

- demo: https://xieziyu.github.io/ngx-echarts/#/basic/basic-usage

**Comment by parvezshah** [comment]
thank you  chart.setOption() worked
