### ISSUE TITLE
echarts 不显示也不报错

### ISSUE THREAD

**Issue by hevan** [xieziyu/ngx-echarts#25]
使用ng2-admin 引入 echarts 不报错，也不显示

**Comment by xieziyu** [comment]
@hevan 
对于ng2-admin，你需要在 `config/webpack.common.js` 中的`ProvidePlugin`配置里面添加echarts的引用：

```javascript
new webpack.ProvidePlugin({
  ...,
  echarts: "echarts"
}),
```

**Comment by hevan** [comment]
Thanks, 
但是我用的是ng2-admin 当前的版本，采用的是angular-cli 方式 ，采用的@ngtools，我需要在对应的@ngtools 增加么？angular-cli.json 已经添加
   "../node_modules/echarts/dist/echarts.min.js"

**Comment by xieziyu** [comment]
@hevan 如果是当前采用angular-cli的版本，则不需要额外的配置。对于这个不显示的问题，需要检查你的参数了，是否传入ngx-echarts的options为空？

**Comment by hevan** [comment]
@xieziyu options 有值，Echarts 没有渲染，不知道是不是用的angular-cli ， 1.3.x的原因

**Comment by xieziyu** [comment]
@hevan angular-cli版本对此没有影响，我们自己的项目中用的也是1.3.x版本。需要看具体的代码片段来确定问题

**Comment by jianping-grp** [comment]
哥们，你怎么解决的。同样的问题。没有渲染

**Comment by monkey-yu** [comment]
同上，同样的问题。  options 有值，Echarts 没有渲染 。 怎么解决的 ，求回复

**Comment by monkey-yu** [comment]
我的问题解决了 ，可以了 。 写了高度的css 文件忘记引入到@Component 里了，偶然写为行内样式可以了。
