### ISSUE TITLE
registerMap  china-cities.json error

### ISSUE THREAD

**Issue by carrie-xin** [xieziyu/ngx-echarts#255]
I'm using ngx-echarts to render china cities map on my dashboard,
but somthing error happend 
![image](https://user-images.githubusercontent.com/53553586/89019681-419eec00-d350-11ea-8657-c731c2ab282a.png)

here's my package version and main code

- angular version:  7.1.0
- echarts: 4.2.1
- ngx-echarts: 4.2.1

```
 <div class="chart-wrapper">
     <div class="chart-div" echarts [options]="chinaMapOption" (chartInit)="chinaMapInit($event)"
            [autoResize]="true"></div>
 </div>
  
  // components
  import * as echarts from "echarts";
  import * as citiesJson from "echarts/map/json/china-cities.json";

  private  mapValue = [
    {
      name: "北京市",
      value: [116.407526, 39.90403, 4133000, "35"]
    },
    {
      name: "上海市",
      value: [121.473701, 31.230416, 1951000, "16"]
    }];

  public chinaMapOption= {
    geo: {
      map: 'china',
      ...
    },
    series: [
      {
        name: 'dashboard',
        type: 'scatter', 
        coordinateSystem: 'geo', 
        data: this.mapValue 
        ...
      }
    ]
  };
  
  public chinaMapInit(ec) {
   echarts.registerMap('china', citiesJson);
    this.instance.chinaMap = ec;
  }
```
Is there anyway to solve this problem?

**Comment by xieziyu** [comment]
@carrie-xin 
You need to registerMap before you try to init the echarts. You can call it in `app.module.ts` or somewhere else

**Comment by carrie-xin** [comment]
@xieziyu thank you for your response, but it seems the problem of import  json,
when i change 

 ```
import * as citiesJson from "echarts/map/json/china-cities.json";
```
to
 ```
import  citiesJson from "echarts/map/json/china-cities.json";
```
it works fine for me.

**Comment by henriquechagasg** [comment]
> @carrie-xin You need to registerMap before you try to init the echarts. You can call it in `app.module.ts` or somewhere else

Whats the best way to do that ?
