### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Tre665** [xieziyu/ngx-echarts#257]
Hello,

thank you for this wonderful project. We are currently investigating some chart lib alternatives and this lib seems to be great from the first impression 👍 

Unfortunately I don't see a specified license for this project. Without a specified license we unfortunately cannot use it. 
My question would be, was it just forgotten to add an open source licence file?

Thank you in advance

**Comment by xieziyu** [comment]
Thank you. I will add an MIT license back to the package.

**Comment by Tre665** [comment]
Wow, that was lightning fast :D 
Thank you for your quick response!
