### ISSUE TITLE
Dynamic Height

### ISSUE THREAD

**Issue by webjunkie01** [xieziyu/ngx-echarts#259]
Hi, I would like to know if it's possible to set a height based on the chart data or via css. I have a vertical bar chart that sometimes displays more data reaching the static height I have sett and the chart becomes unreadable.

**Comment by Manfice** [comment]
I solve this problem by re init echart instance according container size params.
Example:
`
  public onResize(elementSize: IElementSize): void {
    this.containerSize = elementSize;
    this.initChart(this.chartModel);
  }

  public initChart(data: ILayout): void {
    if (this.chartInstance) {
      this.chartInstance.dispose();
    }

    this.chartInstance = echarts.init(document.getElementById(this.componentId) as HTMLDivElement, LIGHT_THEME, {
      devicePixelRatio: 1,
      height: this.containerSize.height,
      width: this.containerSize.width,
    });

    this.chartInstance.setOption(this.service.prepareDataForChart(data));
    this.registerEChartsEvents();
  }

`

**Comment by webjunkie01** [comment]
@Manfice awesome!, thanks.
