### ISSUE TITLE
饼图出现缺某一块现象

### ISSUE THREAD

**Issue by kvent2016** [xieziyu/ngx-echarts#26]
点击饼图某一块时，重新设置options，出现startAngel of undefined并缺少某一块。但使用搜索或其他方式调用同样方法更新options却无此现象。

**Comment by xieziyu** [comment]
@kvent2016 从你的描述中，我无法确定问题具体的表现，请提供一下相应的代码片段或者模拟代码，从而帮助定位问题

**Comment by kvent2016** [comment]
onChartClick(event){ 
    this.parentEchart = true;         
  }
比较得出问题所在如上所示，执行(chartClick)="onChartClick($event)  该方法，点击后parentEchart输出为true,但html绑定的依然是false。
留个QQ可以吗，或者286507295加下我，感谢！

**Comment by xieziyu** [comment]
目测这个issue和#28 是同一个情况，我会抽空将这个问题fix掉。

**Comment by xieziyu** [comment]
@kvent2016 我还是没法复现这个问题。我测试了angular能够正确检测chartClick事件处理函数内部的模型变化。

**Comment by SaErNuoSi** [comment]
@xieziyu #28这个问题有没有修复。。我使用的最新的2.0在点击barChart以后。想更新另外一个pieChart.发现视图没有发生变化
[source.zip](https://github.com/xieziyu/ngx-echarts/files/1545378/source.zip)

**Comment by xieziyu** [comment]
@SaErNuoSi @kvent2016 
Thanks for your comments. This issue should be fixed in v2.0.1. I will publish it soon.
