### ISSUE TITLE
Incompatible peer dependency to "tslib" when upgrading my application to Angular 10

### ISSUE THREAD

**Issue by RozennK** [xieziyu/ngx-echarts#260]
When trying to upgrade my application from Angular 9 to Angular 10 I got the following error:

> Package "ngx-echarts" has an incompatible peer dependency to "tslib" (requires "^1.10.0", would install "2.0.1").

Strangely I don't recall this issue when upgrading a different library that also had this dependency... Is this something anybody has run into? The latest version of ngx-echarts appears to use Angular 9, is there one using Angular 10?

Thank you for your time.

**Comment by xieziyu** [comment]
`tslib` is automatically added to `peerDependency` when using `ng build`.
Please refer to this issue:
https://github.com/ng-packagr/ng-packagr/issues/1159

Need to upgrade the whole project to Angular 10.

**Comment by Rapiiidooo** [comment]
Please consider migrated to angular 10 `ngx-echarts@5.1.2 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.`

Would be nice to update the latest dependencie version of ngx-echarts to the latest version of tslib.

Thanks

**Comment by qortex** [comment]
Same here

**Comment by xieziyu** [comment]
Please use `ngx-echarts@6.0.0-alpha.1`
