### ISSUE TITLE
ECharts 5: registerLocale

### ISSUE THREAD

**Issue by jenswet** [xieziyu/ngx-echarts#290]
Hello,

ECharts 5 introduced the `registerLocale` option: https://echarts.apache.org/en/api.html#echarts.registerLocale

Is it possible to use this option with `ngx-echarts`?

When I looked through the source correctly, it's not yet possible and I would have to add it here: https://github.com/xieziyu/ngx-echarts/blob/f020c6a32e9f5ce743b884d2e97644a33e38c525/projects/ngx-echarts/src/lib/ngx-echarts.directive.ts#L191

Am I right? I might do a PR then. Should we add this as another Option like the `initOpts`?

Thanks and regards!

**Comment by xieziyu** [comment]
Hi, did you try to use `echarts.registerLocale` function?
```ts
// app.module.ts
import * as echarts from 'echarts'

echarts.registerLocale(...)
```

**Comment by jenswet** [comment]
Hi @xieziyu,

I think I misunderstood the documentation from ECharts.

I'd like to use `DE` als locale. Since `DE` is already part of the translated languages I should not need to register it (?).

See https://echarts.apache.org/en/api.html#echarts.init
> **locale**: Specify the locale. There are two builtins: 'ZH' and 'EN'. Or you can use echarts.registerLocale to register a new locale. Or supported locales can be referenced in src/i18n

I tried the following:

chart-module.ts
```typescript
initOpts = {
    locale: 'DE'
  }
```

chart-module.html
```typescript
<div echarts [initOpts]="initOpts" [options]="chartOption" [merge]="chartData" class="chart"
                 (chartInit)="onChartInit($event)"></div>
```

This gives a type hint error:
> Type {locale: string} is not assignable to type {devicePixelRatio?: number, renderer?: string, width?: number | string, height?: number | string} 

I guess this is because the `local` option is not yet part of the [input specification](https://github.com/xieziyu/ngx-echarts/blob/f020c6a32e9f5ce743b884d2e97644a33e38c525/projects/ngx-echarts/src/lib/ngx-echarts.directive.ts#L35). I can do a PR for that.

But apart from the type error the chart is not translated to german. Only the languages `EN` and `ZH` take effect. Do you know how I need to reference the languages from `src/i18n`?

**Comment by jenswet** [comment]
I think I got it, when I add `import 'echarts/i18n/langDE';` to my `app.module.ts` the translation to `DE` is working as expected.

Do you know if this the correct usage of the feature?

**Comment by WissemAouichi** [comment]
Hello i'm stuck with this. Can you please give us more details on how this worked for you in an angular app ? @jenswet @xieziyu

**Comment by jenswet** [comment]
Hi @WissemAouichi, which language do you try to use?

**Comment by jenswet** [comment]
Hi @calogar,

this is the full working code excerpt from my project:

```ts
import {NgxEchartsModule} from "ngx-echarts";
import * as echarts from 'echarts/core';
import {LineChart} from 'echarts/charts';
import {DataZoomComponent, GridComponent, LegendComponent, MarkLineComponent, TimelineComponent, TitleComponent, TooltipComponent} from 'echarts/components';
import {CanvasRenderer} from 'echarts/renderers';
import langDE from 'echarts/lib/i18n/langDE';

echarts.use([LegendComponent, MarkLineComponent, GridComponent, TitleComponent, TimelineComponent, TooltipComponent, CanvasRenderer, DataZoomComponent, LineChart])
echarts.registerLocale("DE", langDE)

@NgModule({
  imports: [NgxEchartsModule.forRoot({echarts})],
  declarations: [],
  providers: [],
  bootstrap: [AppComponent]
})
```

It looks like the main difference is that I am importing from `lib` and you don't, but I don't know why that should be a problem...

Your component initOpts are exactly the same as mine (except DE/FR).

**Comment by calogar** [comment]
Hello again @jenswet, thanks for the answer.

Importing from lib did not change anything. I thought the issue could be with my `NgxEchartsModule.forRoot` not being in AppModule (is in a chart-utility module that other modules import), so I moved it to AppModule, I did everything as in your example and put a basic chart in app.component. Still no luck.

I am using Angular 9 with ngx-echarts 5.2.2, as that is the recommended version. Can this be the problem?

**Comment by jenswet** [comment]
Hi @calogar,

I currently use the following versions:
```
"@angular/core": "~12.1.1",
"ngx-echarts": "^7.0.1",
"echarts": "^5.1.2",
```

I think the first working version from February had these versions according to my project git:
```
"@angular/core": "^10.2.4",
"ngx-echarts": "^6.0.0",
"echarts": "^5.0.1",
```

**Comment by calogar** [comment]
Then I guess my only alternative is to upgrade to a newer version of Angular. Thanks!

**Comment by augustoicaro** [comment]
Same problem here.

My package versions are:
``` yml
"@angular/core": "^11.2.13",
"echarts": "^5.1.2",
"ngx-echarts": "^7.0.1",
```

Just register the language by itself doesn't solve the problem. We need to add `locale` as `initOpts` property.

I followed @jenswet instructions, but I had no success.

**Comment by augustoicaro** [comment]
Ok, I cloned the repo and did the modification, and now it is working.

One important thing is that you need to register the locale and change locale options even to default locales, as you need to do in echarts(see this [example](https://jsfiddle.net/ydac567f/)).

I submitted a PR https://github.com/xieziyu/ngx-echarts/pull/322 that solves this problem.

**Comment by jenswet** [comment]
Hi @augustoicaro,

happy to see you did a PR to update the Readme and add the locale to the initOpts interface.

But if I checked the changes correctly there are no real changes that make it work (except the fixed linter problem about initOpts) or did I miss something? My instructions above (registering the locale and adding the initOpts) should still be valid?

Thanks for the PR anyways, hope @xieziyu will accept it!

**Comment by augustoicaro** [comment]
@jenswet The problem, in fact, only exists in angular 12+ or projects with strict mode on (that now is enabled by default and it is a good practice). Because you can't add a property to type or erase the type of code outside your project. As `locale` wasn't an expected property, there is nothing to do in strict mode. 

In addition to https://github.com/xieziyu/ngx-echarts/issues/290#issuecomment-880494870, I just set `locale` in `initOpts` of your HTML object and put in words the requirement of register the local even the built-in locales.

**Comment by jenswet** [comment]
Hi @augustoicaro,

I've disabled the strict mode because of this, but I am happy to see I can re-enable it with the next update.

I've wrote about initOpts in the html object in https://github.com/xieziyu/ngx-echarts/issues/290#issuecomment-773924242 already, but anyhow - great that it works now for everybody!

**Comment by anton-khimich** [comment]
Hi @jenswet, sorry to reopen this conversation, but how did you manage to import the locales in the first place? On my end I get a compiler error:
`Error: src/app/app.module.ts:7:20 - error TS7016: Could not find a declaration file for module 'echarts/lib/i18n/langFR'. 'C:/Users/Anton/demo-angular/demo/node_modules/echarts/lib/i18n/langFR.js' implicitly has an 'any' type.
  Try npm i --save-dev @types/echarts if it exists or add a new declaration (.d.ts) file containing declare module 'echarts/lib/i18n/langFR';`

`7 import langFR from 'echarts/lib/i18n/langFR'`

**Comment by augustoicaro** [comment]
@anton-khimich when I di the PR I updated the [README](https://github.com/xieziyu/ngx-echarts#custom-locale). Take a look at the custom locale section.

**Comment by anton-khimich** [comment]
Hey @augustoicaro , thanks for replying. I added `"esModuleInterop": true` to my `tsconfig.json`, but the error still remains. Any other advice?

**Comment by augustoicaro** [comment]
Hum... witch echart version are you using? My version(5.1.2) doesn't have `d.ts` files

**Comment by anton-khimich** [comment]
I'm on version 5.2.2 .

**Comment by augustoicaro** [comment]
Oh! I found it! I was looking at the wrong path. Yes! this is the answer. Just import the type that the file defines a module: `import langFR from 'echarts/types/src/i18n/langFR'`

**Comment by augustoicaro** [comment]
That's odd. I write the section wrong. I tried the section code and have the same problem as you. I will create a PR with this update. Thanks for pointing the mistake.

**Comment by anton-khimich** [comment]
Unfortunately, the new import still gives me an error: 
`./src/app/app.module.ts:6:0-51 - Error: Module not found: Error: Can't resolve 'echarts/types/src/i18n/langFR' in 'C:\Users\Anton\demo-angular\demo\src\app'` .

**Comment by augustoicaro** [comment]
Sorry for the previous replies. That is very odd. I'm sure that I tested what I wrote in the README, but in fact, it doesn't work. So if you look at the language file `echarts/lib/i18n/langFR`, it only has a function that registers the language object. But for our use, we need to register the language in our echart object. So, the conclusion is that we can't use this file as it is in typescript.

My suggestion is only copying the language object inside the language file that you want and do as follow:
```js
import {NgxEchartsModule} from "ngx-echarts";
import * as echarts from 'echarts/core';
// import langFR from 'app/shared/langFR'; // you can define your object in a separated file, or

const langFR = { ... }; // paste the language object from language file.

echarts.registerLocale("FR", langFR)

@NgModule({
  imports: [NgxEchartsModule.forRoot({echarts})],
  declarations: [],
  providers: [],
  bootstrap: [AppComponent]
})
```

app/shared/langFR.ts
```js
export default {...} // paste the language object from language file.
```

**Comment by anton-khimich** [comment]
Thanks for all the help Augusto, everything works well now. It seems a little weird that the maintainers of `echarts` added the declaration files for the locales (like `echarts/types/src/i18n/langFR.d.ts`), but we can't seem to use them here. Maybe we are missing something or the maintainers are? Either way, thank you very much for everything.

**Comment by augustoicaro** [comment]
I agree. But echarts was written for javascript and there it worked as expected. So the language import that register the language in echart object works well in plain js, but for us, we need to register in our echart object and not in a new echart object instance. A solution can be ngx-echarts provide the language files as should be. @xieziyu what do you think? I can create a PR for this.

**Comment by Nurech** [comment]
@augustoicaro I am not sure why you are so sure that importing the language file does not work as expected. 

I created my custom lang file `langEE.ts`
```javascript
export default {
// ...
};
```

Imported it to AppModule
```javascript
import langEE from './shared/charts/combo-echart/langEE';
import * as echarts from 'echarts';
echarts.registerLocale("EE", langEE)
```
Started using it on chart load.
```javascript
  initOpts = {
    locale: 'EE',
  };
```
```html
<div echarts [options]="chartOption" [initOpts]="initOpts" class="demo-chart"></div>
```

package.json
```
    "echarts": "^5.3.0",
    "ngx-echarts": "^7.1.0",
```

**Comment by augustoicaro** [comment]
@Nurech, you did right. The problem isn't with the custom lang files. They are working well. This is how I'm using it in production in my project. But the problem is with the languages files provided in echart package, as I explained in https://github.com/xieziyu/ngx-echarts/issues/290#issuecomment-963366866. The files in `echarts/i18n/*.js` don't work for us due to `no implicit any type rule` that strict mode use. So you will get the same error as @anton-khimich described.

**Comment by GO3LIN** [comment]
The solutions proposed here doesn't make sense for me (copying and pasting a built-in locale into another variable)...

So, I just told TypeScript to ignore import error and it worked, like this:

/```
/ @ts-ignore
import langFR from 'echarts/lib/i18n/langFR';
```

Until, this gets fixed by echarts.
