### ISSUE TITLE
contextmenu是否考虑增加一下？

### ISSUE THREAD

**Issue by yinyihui** [xieziyu/ngx-echarts#3]
echarts V3中有contextmenu事件，是否考虑增加一下这个emitter？
![image](https://cloud.githubusercontent.com/assets/13214503/26623760/512c00b4-4621-11e7-903f-e8edac44b768.png)

**Comment by xieziyu** [comment]
@yinyihui 已发布新版本v1.2.1支持

**Comment by yinyihui** [comment]
赞
