### ISSUE TITLE
Directive theme input should also accept object

### ISSUE THREAD

**Issue by Plutoz01** [xieziyu/ngx-echarts#306]
Hi everyone,

Based on latest [documentation](https://echarts.apache.org/en/api.html#echarts.init), a given chart can be initialized with not just a predefined theme name but also can accept a given theme object as well.

I'd suggest to modify Directive's theme input type signiture to:

``` typescript
import { ThemeOption } from 'echarts/types/src/util/types';
// ...
export class NgxEchartsDirective implements OnChanges, OnDestroy, OnInit, AfterViewInit {
// ...
  @Input() theme: string | ThemeOption;
// ...
}

```

**Comment by xieziyu** [comment]
Thanks. It's supported in v7

**Comment by Plutoz01** [comment]
Thanks for the fix!
