### ISSUE TITLE
Tooltips are not contained within window

### ISSUE THREAD

**Issue by TaylorShane** [xieziyu/ngx-echarts#307]
On small screens tooltips partially appear outside the browser window. They should instead be bound to the confines of the browser window so all content can be read.

Version:
"@angular/animations": "-11.2.1",
"@angular/common": "~11.2.1",
"@angular/compiler":"-11.2.1",
"@angular/core": "~11.2.1",
"@angular/forms": "-11.2.1",
"@angular/localize": "~11.2.1",
"@angular/platform-browser": "-11.2.1
"@angular/platform-browser-dynamic": "-11.2.1",
"@angular/router":"-11.2.1",
"bootstrap": "^4.6.0",
"echarts": "^5.0.2",
"ngx-bootstrap": "^6.2.0",
"ngx-echarts": "^6.0.0",

![Screenshot_20210424-184605.png](https://user-images.githubusercontent.com/26348898/115975769-62861d80-a52d-11eb-8783-122eee144b4b.png)

**Comment by chuck0523** [comment]
Did you try `confine` option ?

If not, try setting below

```js
tooltip: {
  confine: true
}
```

ref: https://echarts.apache.org/en/option.html#tooltip.confine

**Comment by TaylorShane** [comment]
Thanks Chuck! I got lost in the mass of documentation and didn't see this optional argument.
