### ISSUE TITLE
请问angular-cli项目的环境中，npm引入后报如下 Warining该如何解决？

### ISSUE THREAD

**Issue by ccm417** [xieziyu/ngx-echarts#31]
用angular-cli组装的工程中，
npm顺利安装了"echarts": "^3.7.1", 以及 "ngx-echarts": "^1.2.4",
也在.angular-cli.json中添加了引用：
"scripts": [
        "../../node_modules/echarts/dist/echarts.min.js"
      ],
然后在moudle中也顺利引入了import { AngularEchartsModule } from 'ngx-echarts';

但是编译的时候报了两个警告：
WARNING in ./~/_@angular_core@4.4.3@@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./~/_@angular_core@4.4.3@@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression

运行时报错：
Uncaught Error: Unexpected value 'AngularEchartsModule' imported by the module 'ScalepageModule'. Please add a @NgModule annotation.

请教大家，这是什么原因？该如何解决，非常感谢。

**Comment by xieziyu** [comment]
@ccm417 看script配置，推测你的项目应该不是单纯用angular-cli组织的，是否使用了webpack或者类似的其他库？如果是的话，需要更改一些对应的config

**Comment by ccm417** [comment]
感谢回复，项目是由angular cli本身的ng new生成的项目，内部应该是以webpack来组织的。

经过反复的删除及重装后终于正常了，因为现在的各个配置没发现跟最初有什么区别，所以只能判断是项目工程中各种包的冲突了吧。谢谢。
