### ISSUE TITLE
Axis not properly fit into grid 

### ISSUE THREAD

**Issue by zubair-saif** [xieziyu/ngx-echarts#316]
hi am trying to use mix-line-bar chart am facing one issue with in below picture is highlited axis of charts not properly fit into grid is there any solution thanks in advance 
![image](https://user-images.githubusercontent.com/11749126/122637826-1957e180-d10a-11eb-83d0-90b5d54bfb2f.png)

**Comment by zubair-saif** [comment]
@zgldh @ThomasBower @debuggerpk @Ghostbird kindly suggestion me some solution for it

**Comment by zgldh** [comment]
Try this option
https://echarts.apache.org/zh/option.html#yAxis.offset

**Comment by zubair-saif** [comment]
> Try this option
> https://echarts.apache.org/zh/option.html#yAxis.offset

thanks its working
