### ISSUE TITLE
如何清除缓存（饼图为例，最新数据为空时，保留上次图表内容）

### ISSUE THREAD

**Issue by kinglongRen** [xieziyu/ngx-echarts#32]
如何清除缓存（饼图为例，最新数据为空时，保留上次图表内容）
1)setOption以及将对应数据置空，仍然不能清除缓存；

**Comment by xieziyu** [comment]
@kinglongRen 有两种方式：
1) options为空的时候，利用*ngIf销毁echarts所在的DOM
2) echarts提供clear()方法，所以在(chartInit)中获取到echarts实例后缓存下来，并在需要的时候，调用clear()方法。

**Comment by kinglongRen** [comment]
采用echarts提供clear()方法，所以在(chartInit)中获取到echarts实例后缓存下来，并在需要的时候，调用clear()方法 问题解决
