### ISSUE TITLE
@juggle/resize-observer should not be a required dependency

### ISSUE THREAD

**Issue by tmtron** [xieziyu/ngx-echarts#328]
When we add  @juggle/resize-observer our angular change detection runs constantly, causing major performance issues.   
Unfortunately we couldn't track it down yet and provide a simple reproduction. 

Anyway: As I understand this, [@juggle/resize-observer](https://www.npmjs.com/package/@juggle/resize-observer) is only a polyfill that is needed by applications that target older browsers, that don't have the native [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver): i.g. IE11
And since it's a polyfill, it should be up to the users to decide, if they need this or not.  

However in the current version 7.0.2 we MUST install @juggle/resize-observer, because it is imported in the source-code (see [ngx-echarts.directive.ts ](https://github.com/xieziyu/ngx-echarts/blob/v7.0.2/projects/ngx-echarts/src/lib/ngx-echarts.directive.ts#L16))  
Instead, the ngx-echarts source code should only use `window.ResizeObserver` and it should be up to the users to decide if they want to use a polyfill (and which polyfill they want to use).  
i.e. when loading the app they could "install" the polyfill, es explained in [Switching between native and polyfilled versions](https://github.com/juggle/resize-observer#switching-between-native-and-polyfilled-versions
)

Backreference: 757

**Comment by inorganik** [comment]
I ran into this issue as well, and was able to roll back to ngx-echarts@5.2.2. Still works well, though I can do longer do a custom build, because of an error complaining about GridComponent. 

Working:
```json
    "echarts": "^5.2.1",
    "ngx-echarts": "^5.2.2",
    "@angular/core": "~11.2.3",
```

```ts
  ...
  imports: [
    ...
    NgxEchartsModule.forRoot({
      echarts: () => import('echarts'),
    })
```

**Comment by tmtron** [comment]
I think this is related to #330

**Comment by marshalltower** [comment]
Yup, having the same issue.

**Comment by xieziyu** [comment]
The polyfill is removed since `v7.1.0 / v8.0.0`
