### ISSUE TITLE
On the usage of the [merge] property

### ISSUE THREAD

**Issue by sir-ion** [xieziyu/ngx-echarts#349]
I have a question about the usage of the `[merge]` property.
Consider the following component:

```ts
import { EChartsOption } from 'echarts';

@Component({
  selector: 'my-chart',
  template: '<div echarts [options]="options" [merge]="merge"></div>',
})
export class MyChart implements OnInit {
  options: EChartsOption = {
     // here goes a long configuration object
  };
  merge: EChartsOption = {}

  ngOnInit() {
    this.setTitle();
    this.setToolboxFeature();
  }

  setTitle() {
    this.merge = { title: { titleText: 'myTitle' } };
  }

  setToolboxFeatures() {
    this.merge = { toolbox: { feature: { saveAsImage: {} }}}
  }
}
```

When this component is rendered only the 'saveAsImage' icon is visible in the toolbox and the title is missing.
I suppose that this is due to the fact that Angular runs the change detection only once after the completion of the `ngOnInit` method, hence only the last value assigned to `this.merge` is applied (indeed, if I switch the order of `this.setTitle()` and `this.setToolboxFeature()` inside that method, I can see the title but not the toolbox).

Am I right? Is this a limit of this approach or is there a way to solve this problem?

Please note that the component above is extremely simplified: in my real use case I need to call methods like `setTitle()` and `setToolboxFeatures()` inside functions that are run when some observables emit values, hence I can not apply all changes from the same place.
However, I would like to keep the handy feature to just "signal" to echarts only the actual changes for the configuration object (leaving the library in charge to do the merge operations).

At the moment I am using the `chartInit` hook to get a reference to the echarts instance and manually call `instance.setOption({ ... })` each time that I need to set some parameters.

Thank you!

**Comment by xieziyu** [comment]
@sir-ion 
You are right. Only the last value assigned to `merge` is applied due to the Angular change detection.
`merge` is designed to merge data into existing series. In your case, i suppose you just need to update options like this:

```ts
import { EChartsOption } from 'echarts';

@Component({
  selector: 'my-chart',
  template: '<div echarts [options]="options" [merge]="merge"></div>',
})
export class MyChart implements OnInit {
  options: EChartsOption = {
     // here goes a long configuration object
  };

  ngOnInit() {
    this.setTitle();
    this.setToolboxFeature();
  }

  setTitle() {
    this.options = { ...this.options, title: { titleText: 'myTitle' } };
  }

  setToolboxFeatures() {
    this.options = { ...this.options, toolbox: { feature: { saveAsImage: {} }}};
  }
}
```
