### ISSUE TITLE
异步加载地图报错

### ISSUE THREAD

**Issue by jamessawyer** [xieziyu/ngx-echarts#36]
我想异步加载'china.json'数据，然后再设置 geo: {map: 'china'}, 但是在异步请求之前echarts已经实例化了，出现报错信息： 'Map chinanot exists. You can download map file on'.

代码部分：
`
@Component({
  selector: 'app-geographical-trend',
  template: ` <div echarts [options]="chartOption" class="demo-chart" (chartClick)="onClick($event)" *ngIf="!isLoading"></div>\`
})
class GeographicalTrendComponent implements OnInit {
      isLoading = true;
    chartInstance: any;
    chinaGeo: string;
    chartOption: any = undefined;  // echarts 配置

constructor(@Inject('APP_CONFIG') private config: Object, private http: HttpClient) {
      console.log(config); // { map: "../../assets/maps" }
      this.chinaGeo = config['map'] + 'china.json'; // china.json 地图的地址
      console.log(this.chinaGeo);
      http.get(this.chinaGeo).subscribe((chinaMap) => { // 异步请求数据
        this.isLoading = false;
        echarts.registerMap('china', chinaMap);  // 注册地图
        console.log('init ', chinaMap);

this.chartOption = Object.assign({}, this.defaultOption, {
          geo: {
            map: 'china',  // 声明map
            // roam: true,
            // ...  
          },
          yAxis: {
            data: this.categoryData.slice(0, 10).sort()
          },
          series : [
            {
                name: '选择器',
                // type: 'scatter',
                type: 'map',
                mapType: 'china',
                geoIndex: 0,                 // 同步数据
                coordinateSystem: 'geo',
                roam: true,
                selectedMode: 'single',
                itemStyle: {
                    normal: {
                        label: {
                            show: true,
                            color: '#fff'  // 字体颜色
                        }
                    },
                    emphasis: {
                      label: {
                        show: true
                      }
                    }
                },
                data: this.provsName
            },
            {
              id: 'bar',
              zlevel: 2,
              type: 'bar',
               // ...
              },
            }
          ],
      });
    });
  }
}
`
请问针对这种异步加载的情况有什么解决办法吗？

**Comment by xieziyu** [comment]
@jamessawyer 可以考虑构造路由的Resolver服务，在路由跳转至地图所在component之前，resolve地图数据。

不过，看你贴的代码片段，chartOption是在echarts.registerMap之后才赋值的，那么理论上来说，此时echarts init的实例化是在发生在拿到地图数据之后才进行的，不应该会出现map没注册上的情况。

**Comment by jamessawyer** [comment]
@xieziyu 我看源码中
 ngOnChanges(changes: { [propertyName: string]: SimpleChange }) {
    if (changes['options']) {
      this.onOptionsChange(this.options);
    }
  }
不管options是否为undefined 都会被调用，不知道是为什么，调用onOptionsChange方法后就会创建echarts实例，所以会报找不到map的错误，实际上我打印 chartOption是可以找到map中的数据的，比较困惑。我能想到的一种解决办法是引入'china.js',而不是异步请求'china.json'的方式，不过这种方式我暂时还没尝试。
另外，想请问一下使用Resolver该怎么写呢？

**Comment by xieziyu** [comment]
@jamessawyer 
请注意`onOptionsChange`函数本身，只有在传入的options有效的时候，才会调用`echarts.init()`。
另外需要区分的是`echarts`和`echartsInstance`两个实例。`echarts`是引入echarts依赖后就有的全局对象，`echartsInstance`是只有在调用init方法后才实例化的图表实例。所以，地图的实例化的确是在拿到数据之后才会发生的。所以我觉得那个报错可能另有其因。

异步请求json的实现肯定是OK的，echarts和ngx-echarts本质上都支持，所以可能是实现细节上有什么被忽略了。

至于resolver可以参考angular的官方文档，关于路由守卫的那个章节有具体的官方示例，我就不再赘述。

**Comment by jamessawyer** [comment]
@xieziyu 嗯嗯 谢谢解答 我明天再找找原因

**Comment by jamessawyer** [comment]
使用 import 'china.js'; 之后不会报找不到map china的错误了，但是如果想点击省份异步加载省份的json文件，再注册省份地图，还是会报上面的错误，不知道这是不是个bug

**Comment by jamessawyer** [comment]
问题找到了，要在顶部导入 'echarts'， (⊙o⊙)…
 import * as echarts from 'echarts'; 
否则 echarts.registerMap 没有这个方法，因为之前一直使用的是 declare var echarts: any; 所以使用echarts.registerMap时，tslint也没有报错，谢谢 @xieziyu 大佬的热心帮助，还想问一下我这样引入合不合适？

**Comment by fanslin** [comment]
ng4 如何导入使用地市的地图？比如福建

**Comment by jamessawyer** [comment]
@fanslin 你是通过json还是js文件格式导入？导入之后注册一下就可以了
