### ISSUE TITLE
ERROR TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by kiwibit** [xieziyu/ngx-echarts#361]
Hi, after integrating ngx-echarts in my project (Angular 13.3.0) i received the following error:

<img width="960" alt="img1" src="https://user-images.githubusercontent.com/103120123/172184195-4e9859d5-a511-47d3-a0af-dc8c9a5a6b29.png">

<img width="845" alt="img2" src="https://user-images.githubusercontent.com/103120123/172184281-b1b1feb8-cb13-4201-a7be-14a464da7570.png">

I'm using the directive in the HTML like so:
`<div echarts [options]="chartOption"></div>`
It's a base chartOption, the same defined in the example code on the Github page. Is there something wrong with the dependencies in my project? Can you help me out with this issue? Than You!

**Comment by tryhank** [comment]
How did you solved it?
