### ISSUE TITLE
Upgrade to latest echart version

### ISSUE THREAD

**Issue by BryanYin** [xieziyu/ngx-echarts#37]
Hi ziyu,

thanks for your efforts in this plugin! But we need some new features in echarts 3.7, for example, put sign at end of line chart, can you upgrade to the latest version?

**Comment by xieziyu** [comment]
@BryanYin 
I think `ngx-echarts` already supports echarts 3.7. You just need to update echarts version in package.json, and run `npm install`

**Comment by BryanYin** [comment]
@xieziyu 

thank you! after i update echarts version, now all works as i expected. issue can be closed.
