### ISSUE TITLE
Gauge type series can not use "merge" input

### ISSUE THREAD

**Issue by sneaker102** [xieziyu/ngx-echarts#373]
Hi,

I am building a gauge chart that looks like this:
![image](https://user-images.githubusercontent.com/45992275/194005587-91e611a8-351d-444d-a14e-257ca5da1212.png)

Before implementing the chart in your lib I was creating the options inside echarts example playgraund.
These are the options: 
[gouge-thresholds.txt](https://github.com/xieziyu/ngx-echarts/files/9713680/gouge-thresholds.txt)

The issue that I have with your lib is that I can not use the "merge" input of your directive as I did into the playground with the "setInterval" function.

When I provide into the "merge" the data series like this:
![image](https://user-images.githubusercontent.com/45992275/194006956-245dcb6d-7e34-4393-8993-ceab27989794.png)
This errros will appear:
![image](https://user-images.githubusercontent.com/45992275/194007147-84e6a6e6-2e8c-470f-90cc-79c3b8ffeb50.png)
![image](https://user-images.githubusercontent.com/45992275/194007269-e3204ab7-f26e-4a8d-a0e1-15fe6d01e3bc.png)

Having this errors the graph will never refresh again.

If the "merge" is undefined than no errors will be thrown but I will get a flickering on the axis labels at init.

Maybe I am doing something wrong and I would like to hear your opinion on this.

Thanks for your work,
Razvan I.

**Comment by xieziyu** [comment]
`merge` is used to update options after the chart is initialized. So you can try to provide `merge` object after delaying for some time, for example, assign `merge` within `setTimeout` or `setInterval` callbacks

**Comment by sneaker102** [comment]
Thanks for the fast response but I've tried to delay the merge object and I still have the same errors.
I have also to mention that for line and bar charts it works as expected.

**Comment by xieziyu** [comment]
Hi, @sneaker102 
I create a demo using your chart options:
https://jake.stackblitz.com/edit/ngx-echarts-issue-373?file=src/app/app.component.ts
but it works as expected.
Maybe you can provide more details about your codes that I need to reproduce the issue.
