### ISSUE TITLE
Legend unselect event is not working

### ISSUE THREAD

**Issue by sarlemon** [xieziyu/ngx-echarts#384]
I follow ngx-echarts guide to bind legend unselect event, but it seems like not working. When I clicked the legend and unselected it, this function is not triggered.
![image](https://user-images.githubusercontent.com/20472625/215932725-7d14e447-52a9-4f46-b558-1e24aa9e8292.png)
![image](https://user-images.githubusercontent.com/20472625/215932766-37fcf759-f586-4807-8545-1da471a99831.png)

**Comment by xieziyu** [comment]
It seems Echarts has deprecated the `legendunselected` event since v2.
You can use [chartLegendSelectChanged](https://echarts.apache.org/en/api.html#events.legendselectchanged) instead.

**Comment by sarlemon** [comment]
Thank you so much.
