### ISSUE TITLE
[loading] property binding is not working .  

### ISSUE THREAD

**Issue by Harshavardhan-Kanoj** [xieziyu/ngx-echarts#391]
when [loading] = true, it's not showing loading animation.Please fix this issue as soon as possible.

**Comment by Harshavardhan-Kanoj** [comment]
@xieziyu , Could you please look into this.
Thank you!

**Comment by xieziyu** [comment]
@Harshavardhan-Kanoj 
Thanks for your feedback. Is it the case that the loading animation is not displayed when the chart has not been initialized yet?

**Comment by xieziyu** [comment]
It should be fixed in v15.0.3. 
I update the [online demo page](https://xieziyu.github.io/ngx-echarts/#/basic/basic-usage) to show `[loading]=true` by default.

**Comment by Harshavardhan-Kanoj** [comment]
> @Harshavardhan-Kanoj Thanks for your feedback. Is it the case that the loading animation is not displayed when the chart has not been initialized yet?

Yes.

**Comment by Harshavardhan-Kanoj** [comment]
> It should be fixed in v15.0.3. I update the [online demo page](https://xieziyu.github.io/ngx-echarts/#/basic/basic-usage) to show `[loading]=true` by default.

When v15.0.3 will be available. 
Thank you!

**Comment by xieziyu** [comment]
> When v15.0.3 will be available?

It's already published, @Harshavardhan-Kanoj

**Comment by Harshavardhan-Kanoj** [comment]
> > When v15.0.3 will be available?
> 
> It's already published, @Harshavardhan-Kanoj

Thank you!

**Comment by Harshavardhan-Kanoj** [comment]
@xieziyu , It's still not working. I am trying to load animation upto 5sec then to show up chart . it's showing blank page for 5 sec and after that showing chart directly.
<img width="1728" alt="Screenshot 2023-03-27 at 11 29 12 AM" src="https://user-images.githubusercontent.com/121387705/227853487-2d31e5c7-c8f4-4b2b-9cdc-537267a3eabc.png">

<img width="1728" alt="Screenshot 2023-03-27 at 11 30 23 AM" src="https://user-images.githubusercontent.com/121387705/227853592-971521e3-7b8c-4bd3-8598-30e25d22c750.png">

![2023-03-27 11 31 58](https://user-images.githubusercontent.com/121387705/227854380-2a9fe85b-7b7c-4588-82bf-ad3b56b2c8c6.gif)
Note:I am using "ngx-echarts": "^15.0.3",
Please look into this . 

Thank you!.

**Comment by Harshavardhan-Kanoj** [comment]
It's working perfect.
Thank you!.

**Comment by xieziyu** [comment]
Great to hear that.
I will close this issue.
