### ISSUE TITLE
display context menu only when right clicked on bar 

### ISSUE THREAD

**Issue by MussaratAziz** [xieziyu/ngx-echarts#395]
Hi everyone,  is there any way to display the custom context menu only when right clicked on bar/series not any where else on chart. Any help will be appreciated.  Thanks @xieziyu

**Comment by xieziyu** [comment]
@MussaratAziz 
You can check the event.componentType in handler: `(chartContextMenu)="onContextMenu"`
```ts
onContextMenu(event) {
  event.preventDefault();

  if (event.componentType === 'series') {
    // TODO: show custom context menu
  }
}
```

**Comment by MussaratAziz** [comment]
Thanks @xieziyu once context menu is visible  if click any where in the chart area context menu displayed again. Is there anything else can be done?

**Comment by xieziyu** [comment]
@MussaratAziz 
I think you need to handle zrender events from the blank. You can refer to [ECharts - Event and Action](https://echarts.apache.org/handbook/en/concepts/event#listen-to-events-on-the-blank-area) for details.

For example:
```html
<div echarts (chartInit)="onChartInit($event)" ... ></div>
```
```ts
onChartInit(myChart) {
  myChart.getZr().on('contextmenu', (event) => {
    if (!event.target) {
      // Clicked on blank.
      event.preventDefault();
      // Do something...
    }
  });
}
```

**Comment by MussaratAziz** [comment]
Thanks @xieziyu
