### ISSUE TITLE
Adding Events from `echarts-gl` into `ngx-echarts`

### ISSUE THREAD

**Issue by Gykonik** [xieziyu/ngx-echarts#396]
First of all, thank you for the amazing Angular directive! I am currently working on rendering huge network graphs, and for that, I need `graphGL` from `echarts-gl` to make the graph performant.

However, I would like to register events from `echarts-gl` (specifically `graphgllayoutstopped`). Is there a way to register additional events? Due to the fact that `this.chart` itself is private, I cannot access the chart object from outside, can I?

I would really appreciate some help, thanks! :)

**Comment by xieziyu** [comment]
Hi @Gykonik 
You can access the chart object after the `chartInit` event emitted.

```html
<div echarts class="demo-chart" [options]="chartOptions" (chartInit)="onChartInit($event)"></div>
```
```ts
onChartInit(chart) {
  // save the chart instance
  this.chart = chart;
  // TODO: something ...
}
```

**Comment by Gykonik** [comment]
Thanks, worked perfectly! :)
