### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'div'?

### ISSUE THREAD

**Issue by fireflysemantics** [xieziyu/ngx-echarts#399]
On stackblitz this it works, but in the standalone CLI environment it errors.

[I provided the Stackblitz and a Github Version of the standalone CLI version that shows the error via this Stackoverflow post.](https://stackoverflow.com/questions/76369537/creating-the-echarts-animated-bar-chart-in-angular-16)

**Comment by derekfreed** [comment]
Same Issue for me

**Comment by xieziyu** [comment]
Please double check your Angular version.
https://github.com/fireflysemantics/charts repo is using Angular 15, so you need install `ngx-echarts@15.0.3`
