### ISSUE TITLE
在*ng-for中无法渲染图表

### ISSUE THREAD

**Issue by lybc** [xieziyu/ngx-echarts#4]
我定义了一个组件名叫`app-pal-line-chart`
```html
<div echarts [options]="options" (chartInit)="onChartInit($event)" class="charts"></div>
```

在另一个组件中想要用ngFor动态渲染多个图表
```html
<div class="pure-u-1-5" *ngFor="let pal of palValues">
    <app-pal-line-chart [palInfo]="pal" [subDateList]="dateList"></app-pal-line-chart>
</div>
```
但是在app-pal-line-chart组件里，ngOnChanges钩子里能够去到pal的值，但是无法取到ecInstance对象。如果不使用ngFor就可以取到。

我不可以循环去创建组件吗？

**Comment by xieziyu** [comment]
@lybc 我自己的项目中有尝试使用`*ngFor`来产生多张图表（同样也自定义了一层组件），所以ngx-echarts本身肯定是支持的。
那么你可能需要定位一下自定义的`app-pal-line-chart`中的问题，如果没有获取到echartsInstance对象，那么很有可能是`options`的数据没有正确绑定传入。你的`pal`值到`options`是怎样传递的？
