### ISSUE TITLE
force directed graph demo broken

### ISSUE THREAD

**Issue by arnoudb** [xieziyu/ngx-echarts#400]
Hi, the force directed graph on: https://xieziyu.github.io/ngx-echarts/#/series/graph
seems to be broken.

**Comment by xieziyu** [comment]
It seems OK in Chrome and Edge. Which browser do you use?

**Comment by arnoudb** [comment]
<img width="1082" alt="Screenshot 2023-06-07 at 11 05 51" src="https://github.com/xieziyu/ngx-echarts/assets/2396055/6ede0b41-e57e-4bdc-b830-b7c1b96e1f22">

Hi, it looks the same on all browsers here (as the picture included). Maybe i'm mistaken but i looked at this a while ago and then it didn't look like circles but like a graph with many connections. So my assumption was that some connections don't work anymore. We are evaluating many libs at the moment so i didn't look into the details, so good chance i'm wrong.

**Comment by xieziyu** [comment]
@arnoudb 
I understand, thank you. The last time I updated, I changed this demo case. So it looks different now.

**Comment by arnoudb** [comment]
Oh sorry, then it's my mistake! Should have looked at the code...

**Comment by arnoudb** [comment]
closing, as i wrongly thought there was an error
