### ISSUE TITLE
实参类型 unknown 不可分配给形参类型 ECElementEvent

### ISSUE THREAD

**Issue by zhang-yanglong** [xieziyu/ngx-echarts#404]
echarts的鼠标事件对应的interface为ECElementEvent
import {ECElementEvent} from 'echarts/types/src/util/types';（"echarts": "5.4.3",）
但我看ngx-echarts的NgxEchartsDirective中声明的EventEmitter都是unknown类型的，能不能改成ECElementEvent呢，这样编辑器就能提示我事件上有哪些属性能用了
而且比较恶心的是，如果我手动标记event类型为ECElementEvent，编辑器还会告警，说
实参类型 unknown 不可分配给形参类型 ECElementEvent
就像这样
html：
(chartMouseOver)="onChartOver($event)"
ts:
onChartOver(e: ECElementEvent) {...}

**Comment by xieziyu** [comment]
Hi,

感谢提醒，刚发布的 v16.1.0 中已添加这些类型
