### ISSUE TITLE
'legendselectchanged' event has no Output

### ISSUE THREAD

**Issue by TBFreaq** [xieziyu/ngx-echarts#408]
Seems like the commit `b72f65f` accidentally removed the `chartLegendSelectChanged` event. Could you please add it back?

**Comment by MussaratAziz** [comment]
Can you please add this even back again. Thanks @xieziyu

**Comment by MussaratAziz** [comment]
@Output() chartLegendSelectChanged = this.createLazyEvent('legendselectchanged');  please add this back again in the 16.1.1 thanks

**Comment by xieziyu** [comment]
Thank you for your suggestions; the issue has been resolved in v16.1.2.
