### ISSUE TITLE
引入html代码直接报错

### ISSUE THREAD

**Issue by robinv8** [xieziyu/ngx-echarts#41]
Can't bind to 'options' since it isn't a known property of 'div'. ("<div class="ant-row">

**Comment by xieziyu** [comment]
Did you import `AngularEchartsModule`?

**Comment by robinv8** [comment]
yes

**Comment by xieziyu** [comment]
抱歉，你需要再检查一下你的代码和模块，这个错误是因为没有正确地引入`AngularEchartsModule`模块造成的。

**Comment by robinv8** [comment]
好的，谢谢
