### ISSUE TITLE
echarts/core -> Implementation of registerMap doesn't exists

### ISSUE THREAD

**Issue by daniel-bunny-net** [xieziyu/ngx-echarts#412]
Hi,
I'm trying to add treeshaking variant, but this method is not found, but should be... Project module is 'commonjs'. It works with no treeshaking if I import from `import('echarts')` and remove `echarts.use()`.

Any ideas, how I must change the code below, so that registerMap exists? I believe it should be added to core.

```
NgxEchartsModule.forRoot({
      echarts: () =>
        import('echarts/core').then((echarts) => {
          const worldJson = 'just some large injected JSON from providers';
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          echarts.registerMap('world', worldJson as any);     <--- this one is failing with  Implementation of registerMap doesn't exists
         
          echarts.use([
            BarChart,
            BrushComponent,
            ChartGridComponent,
            CustomChart,
            DatasetComponent,
            DataZoomComponent,
            EffectScatterChart,
            GeoComponent,
            LabelLayout,
            LegendComponent,
            LineChart,
            MapChart,
            SVGRenderer,
            TitleComponent,
            ToolboxComponent,
            TooltipComponent,
            TransformComponent,
            UniversalTransition,
            VisualMapComponent,
          ]);

          return echarts;
        }),
    }),
```

**Comment by daniel-bunny-net** [comment]
I did try to do it with `provideEchartsCore()` but it doesn't accept config as a `echarts: any | (() => Promise<any>);`... That would be an improvement if it could be done this way.

**Comment by xieziyu** [comment]
According to the official document, there is a BREAKING CHANGE after v5.3:
https://echarts.apache.org/handbook/en/basics/release-note/5-3-0/#registermap-and-getmap-methods-need-to-be-used-only-after-the-map-chart-is-imported

Maybe you can try `echarts.use([MapChart])` firstly and then call registerMap.

**Comment by daniel-bunny-net** [comment]
Thnak you, works now.
