### ISSUE TITLE
热力图的merge接口不能实时更新图表吗

### ISSUE THREAD

**Issue by CoderPoet** [xieziyu/ngx-echarts#46]
dynamic图是可以的 但是热力图好像不会更新？

**Comment by xieziyu** [comment]
@CoderPoet merge接口只要检测到change就会更新。需要看一下你的代码片段，怎么更新merge的接口数据？

**Comment by CoderPoet** [comment]
不好意思，才看到回复，之前报错是由于我这边的问题，修复后就可以了，merge接口没有问题！感谢~
