### ISSUE TITLE
绘制markLine出错

### ISSUE THREAD

**Issue by ccsulzf** [xieziyu/ngx-echarts#54]
Angular Version:5.0

errorInfo:
![image](https://user-images.githubusercontent.com/25943682/34199673-815792f8-e5a9-11e7-8b31-2416bbce00c3.png)

code:
`
我在网上找了一份中国地图数据
 this.es.registerMap('CHINA', geoJson);
不知道是否和这个有关
`

`markLine:[
      data: [
                                 [
                                        { name: '北京' },
                                        { name: '上海', value: 95 }
                                    ],
                                    // [{ name: '北京', x: 40, y: 100 }, { name: '包头', x: 140, y: 100 }],
                                ],
                                geoCoord: {
                                    '上海': [121.4648, 31.2891],
                                    '北京': [116.4551, 40.2539],
                                },
             ]
]`

如果能给出这样的列子,那就更好了
![image](https://user-images.githubusercontent.com/25943682/34199820-f1f8994e-e5a9-11e7-89bb-f908087623c9.png)

**Comment by xieziyu** [comment]
@ccsulzf 这应该不是ngx-echarts的问题。demo中测试过geoJson的数据格式可以绘制。请参考ECharts的文档，检查一下你的options的配置。

**Comment by ccsulzf** [comment]
已经解决了
在 ECharts 3 中不再建议在地图类型的图表使用 markLine 和 markPoint。如果要实现点数据或者线数据的可视化，可以使用在地理坐标系组件上的散点图和线图。
