### ISSUE TITLE
#feature# 是否可以支持非 window resize 影响 导致的 容器变化的 chart 重绘功能

### ISSUE THREAD

**Issue by WallenHan** [xieziyu/ngx-echarts#60]
- 功能
是否可以支持非 window resize 影响 导致的 容器变化的 chart 重绘功能

**Comment by xieziyu** [comment]
建议基于ngx-echarts，在上层封装组件以侦听检测容器的size变化，并调用echarts的resize方法。

**Comment by WallenHan** [comment]
是的， 正在这么考虑， 不过 目前貌似没有支持非  window 对象引起的 dom size变化的检测机制， 感觉得在组件 ngOnInt 中 写一个定时器 来检测， 然后 resize。 但是感觉很脏啊， 不知 你有什么好的建议。

**Comment by WallenHan** [comment]
补充， echart 的 resize 就是 基于 window 的resize 检测来做的， 但是无法检测到基于 document 内容引起的 容器resize 的变化。

**Comment by tinybull** [comment]
@xieziyu
@HostListener('window:resize', ['$event'])
onWindowResize(event: any) {
    if (event.target.innerWidth !== this.currentWindowWidth) {
      this.currentWindowWidth = event.target.innerWidth;
      if (this._chart) {
        this._chart.resize();
      }
    }
  }
 这里设置window高度发生变化时，也重绘一下图表呢

**Comment by xieziyu** [comment]
@tinybull 如果没有特殊需求，不建议根据windows的高度变化去重绘图表。

**Comment by xieziyu** [comment]
@WallenHan 我的理解里面，除去windows窗口拉伸操作之外所产生的容器的size变化，一般是由于某种人为因素触发的改变，也就是说，代码里应该能知道什么时候会发生容器变化， 可以考虑由该容器去emit它的Size变化事件，来触发chart组件的resize()函数调用，这样可以避免启用定时器。
