### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by liangqiliang** [xieziyu/ngx-echarts#67]
您好，我想问下我在ng-alain下使用了插件，报了这个错，是怎么回事呢？
![image](https://user-images.githubusercontent.com/23448294/35603403-344c0468-0678-11e8-866d-fe7883df4697.png)

**Comment by liangqiliang** [comment]
安装了echart和ngx-echarts后都报了这些警告，并且都已经在modules import了
npm WARN ng-zorro-antd-extra@1.1.6 requires a peer of rxjs@>5.x but none was installed.
npm WARN ng2-img-cropper@0.9.0 requires a peer of @angular/common@^4.0.0 but none was installed.
npm WARN ng2-img-cropper@0.9.0 requires a peer of @angular/compiler@^4.0.0 but none was installed.
npm WARN ng2-img-cropper@0.9.0 requires a peer of @angular/core@^4.0.0 but none was installed.
npm WARN ng-alain@0.6.0-rc.2 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by lucienlugeek** [comment]
我跟你遇到了同样的问题，请问你是怎么解决的呢？
