### ISSUE TITLE
可以添加地图图表吗？

### ISSUE THREAD

**Issue by SevenLonelyDay** [xieziyu/ngx-echarts#7]
请不知道你这个插件可以在angular上面做关于地图统计的图表吗？ 比如说引入中国地图，或者某个省份的地图。

**Comment by xieziyu** [comment]
@SevenLonelyDay echarts本身支持的图表，都可以的。

**Comment by SevenLonelyDay** [comment]
恩，搞好了。三克油(*^__^*) 嘻嘻……

**Comment by fei-hao** [comment]
@SevenLonelyDay 你好,请问你的地图是怎么添加的啊(?_?)

**Comment by sadydai** [comment]
@xieziyu 要如何引入地图的json 文件？ echarts.registerMap（）这个怎么用的？

**Comment by xieziyu** [comment]
@sadydai 你可以用http异步加载json文件，然后再使用echarts.registerMap注册。这些操作不需要ngx-echarts的参与

**Comment by sadydai** [comment]
@xieziyu 嗯呢， OK了。谢谢

**Comment by JuniorTour** [comment]
@xieziyu，你好，非常感谢你的作品！

请问有办法在组件的component.ts之中获取到echarts对象的引用，从而更加方便的实现调用echarts.registerMap注册地图以及其它方法和属性吗？

可以通过(chartInit)="onChartInit($event)"获取到chartInstance，那么有没有类似的方法或指令可以实现获取echarts对象呢？

谢谢帮助！麻烦你了。

**Comment by xieziyu** [comment]
@JuniorTour 谢谢。 echarts是全局对象，所以可以直接使用。Typescript中，可以在需要用到的ts文件中：
`declare var echarts: any;`

**Comment by fanslin** [comment]
@SevenLonelyDay 求demo，肿么搞滴，如何引入省份地图？
