### ISSUE TITLE
help, another "echarts is not defined"

### ISSUE THREAD

**Issue by xbu** [xieziyu/ngx-echarts#70]
I used echart, and I follow the document to config the ngx-charts, but find "echarts is not defined" in console, the online demo is here  [echarts demo](https://stackblitz.com/edit/angular-6qwfdv?file=app%2Fapp.component.ts).

you can find the error in console.

env: pure angular

**Comment by xieziyu** [comment]
@xbu I export your code and found that: `.angular-cli.json` is not correctly configured (without scripts). So I think you can't just add a `.angular-cli.json` in your editor's FILES panel. You have to find a way to edit the real `.angular-cli.json` file.

**Comment by xbu** [comment]
@xieziyu I tried again on my PC, but it seems the error stay still. I upload my [demo](https://github.com/xbu/demo) project here.

**Comment by xieziyu** [comment]
Your code is OK. I didn't see the error in your app.
Did you restart `ng serve` after you changed your `.angular-cli.json`?

**Comment by xieziyu** [comment]
![image](https://user-images.githubusercontent.com/6669841/35787985-327da288-0a6d-11e8-8e1c-eea7a0ebd6e9.png)

**Comment by xbu** [comment]
@xieziyu nice, it works.  I thought it would automatically reboot the app. thanks for your time and awesome ngx-echarts.
