### ISSUE TITLE
工具栏中提示信息显示不全

### ISSUE THREAD

**Issue by CC2013** [xieziyu/ngx-echarts#74]
![image](https://user-images.githubusercontent.com/3352426/35951001-5b7b2b6c-0cb4-11e8-8de9-5cc15e543c6d.png)

版本号："echarts": "^3.8.5", "ngx-echarts": "^2.0.1"
显示的下载工具栏处，提示文字被遮挡，是否有办法解决？

**Comment by xieziyu** [comment]
这个应该是echarts的使用问题，容器宽度不够造成的吧？ngx-echarts并没有特殊处理toolbox

**Comment by CC2013** [comment]
谢谢你的回复，我尝试过把宽度变宽，但是文字仍旧被遮挡一部分了，我去echarts官网看了，貌似它也存在这个问题：



 

发件人: Xie, Ziyu [mailto:notifications@github.com] 
发送时间: 2018年2月9日 11:51
收件人: xieziyu/ngx-echarts
抄送: Echo Xiao; Author
主题: Re: [xieziyu/ngx-echarts] 工具栏中提示信息显示不全 (#74)

 

这个应该是echarts的使用问题，容器宽度不够造成的吧？ngx-echarts并没有特殊处理toolbox

**Comment by CC2013** [comment]
已通过配置toolbox{right: 20}解决该问题，我自己的使用问题造成，感谢作者的耐心回复！
