### ISSUE TITLE
如何动态更换主题

### ISSUE THREAD

**Issue by setsunahao** [xieziyu/ngx-echarts#75]
如何动态更换主题
我目前是这样写的,theme的值也变了,但是主题并没有切换过去,
`<div echarts [options]="options" id="themeCharts" [theme]="currentTheme" ></div>`

**Comment by setsunahao** [comment]
我最后这样搞了
`import * as $ from 'jquery';
declare var echarts: any;
  createChart(options : any, theme : string){
    //清空内容
    let container = $("#chartsContainer");
    container.empty();
    //追加图表div
    let child = $("<div id='mychart' style='width:100%;height:500px'></div>");
    child.appendTo(container);
    let chart = echarts.init(document.getElementById("mychart"),theme);
    chart.setOption(options);
  }
`

NgxEchartsService 应该是我不会用吧,调了下init没起作用.能不能文档上加些NgxEchartsService的例子呢，目前感觉还是不够用

**Comment by xieziyu** [comment]
NgxEchartsService的例子在demo里面：
https://xieziyu.github.io/ngx-echarts/#/usage/NgxEchartsService
