### ISSUE TITLE
loading样式修改

### ISSUE THREAD

**Issue by qinqing3761** [xieziyu/ngx-echarts#79]
大神，这里的loading是一个boolean属性，请问我如何修改loading的默认样式呢？就比如把loading改为“加载中……”

**Comment by xieziyu** [comment]
暂时没有提供这个接口。需要的话，可以调echarts的api去showloading：
http://echarts.baidu.com/api.html#echartsInstance.showLoading

**Comment by xieziyu** [comment]
@qinqing3761 新版本v2.1.0提供了[loadingOpts]接口以定义loading样式。谢谢！
我将关闭此issue。
