### ISSUE TITLE
关于echarts设置纵坐标最大值的问题

### ISSUE THREAD

**Issue by zlinwei** [xieziyu/ngx-echarts#81]
默认情况下纵坐标的最大值是随着序列的y值变化的，这里我想固定它。
所以我在options里的yAxis.max :300 这样子设置了，也生效了：
this.chartOption = {
      ...
      yAxis: {
           type: 'value',
           max: 300,
      },
      series: [{
            ...
      }]
    };
但是这样子编译器会报错，虽然正确生效了
 Type '{ type: string; max: number; }' is not assignable to type '{ type: string; }'.
      Object literal may only specify known properties, and 'max' does not exist in type '{ type: string; }'.

**Comment by xieziyu** [comment]
这个可能是由于ts代码某处对chartOption做了类型的隐式推测，认为yAxis的类型是`{ type: string; }`所致。请检查你声明chartOption的代码。并非ngx-echarts或者echarts报的错误

**Comment by zlinwei** [comment]
嗯嗯，已解决，我第一次给这个变量赋值的时候没有这个属性，所以被ts推断成了类型定义。谢谢解答。
