### ISSUE TITLE
Example from README Usage section is not working on angular 5.2

### ISSUE THREAD

**Issue by sashaaro** [xieziyu/ngx-echarts#83]
![2018-03-23 18-12-03-iloveimg-cropped](https://user-images.githubusercontent.com/5504250/37837588-a5079e08-2ec6-11e8-904a-15cc57d90887.png)

**Comment by xieziyu** [comment]
@sashaaro I noticed that `width = 0`. I think this issue is related to some other library. The echarts can't get the width of parent container.

I tried that example in a clean environment and it's working as expected.

**Comment by sashaaro** [comment]
I remove container .mdl-shadow--2dp and fix it. sorry for my fault

**Comment by sashaaro** [comment]
After resize chart appear

**Comment by hmaury1** [comment]
hello @sashaaro 
can you share any code with the solution?

**Comment by sashaaro** [comment]
It start work after call async method from ngOnInit then rewrite echart options property.
```javascript
class MyComponent implements OnInit {
  echartOptions = {} // put any options, anyway not work for me
  ngOnInit() {
     this.statisticsSerivice.findOrderStatistics(...).subscribe((statistics: IOrderStatistics) => {
        this.chartOptions = this.transformToChartOptions(statistics)
      // assigned new object and after charts start appear
     // if you not do async call possible you can try call setTimeout(() => { this.echartOptions = {...this.echartOptions}}, 1) in ngAfterContentInit for trigger echart's change detection 
     })
  }
}
```
