### ISSUE TITLE
How to implement echarts wordcloud with ngx-echarts ?

### ISSUE THREAD

**Issue by Lakston** [xieziyu/ngx-echarts#84]
I'm trying to add a wordcloud to my app using ngx-echarts but can't make it work,$
I added echarts-wordcloud to my cli scripts :

```
 "scripts": [
        "../../../node_modules/echarts/dist/echarts.min.js",
        "../../../node_modules/echarts-wordcloud/dist/echarts-wordcloud.min.js"
      ]
```

and added the options from the wordcloud example to my echartInstance options : https://github.com/ecomfe/echarts-wordcloud/blob/master/example/wordCloud.html

but the `chartInit` is not firing so I don't have an instance of my chart.

Anyone managed to use the word-cloud with ngx-echarts ?

Note : The normal charts are working, I have lines, bars etc... working on my app, only the wordcloud is causing problems.

Thanks

**Comment by SinghB** [comment]
The above was closed, but I want to provide steps of what I had to do to make it work. However, I can't make it work with latest version (>= 4.0) of ngx-echarts. So if anyone knows how to do the following in the latest version, please help.

This is what my `package.json` looks like

```
"echarts": "^4.2.1",
"echarts-wordcloud": "^1.1.3",
"ngx-echarts": "^3.2.0",`
```
And add the following to your `angular.json`:

```
"scripts": [
          "node_modules/echarts/dist/echarts.min.js",
          "node_modules/echarts-wordcloud/dist/echarts-wordcloud.min.js"
]
```
Ensure you've got the import taken care of in your app module:

`import {NgxEchartsModule} from 'ngx-echarts';`

Now in your html file, create the echarts div as:

`<div echarts [options]="wordCloudOptions" [merge]="updateOptions" (chartClick)="wordClick($event)">`

In my TS file, initialize `wordCloudOptions` during `ngOnInit` and then once you've fetched the data for display, push it into `updateOptions`

**Comment by SinghB** [comment]
Figured out the steps to implement this with latest version (>= 4.0) of ngx-echarts.  Note my response earlier for steps that worked with prior version

This is what my `package.json` looks like, note the addition of `@types/echarts` as indicated in documentation when migrating from 3.x to 4.x version

```
    "@types/echarts": "^4.1.9",
    "echarts": "^4.2.1",
    "echarts-wordcloud": "^1.1.3",
    "ngx-echarts": "4.1.1"
```

`angular.json` now with 4.x doesn't need the script inputs

Ensure you've got the import taken care of in your app module:

`import {NgxEchartsModule} from 'ngx-echarts';`

Ensure that `main.ts` imports `echarts-wordcloud`

`require('echarts-wordcloud');`

HTML and TS file of component are like earlier
