### ISSUE TITLE
echarts is not define

### ISSUE THREAD

**Issue by zhuiluo0987** [xieziyu/ngx-echarts#87]
好像webpack.command.js在node-modules里面。这里面的东西能随便改嘛

**Comment by xieziyu** [comment]
@zhuiluo0987 你为什么需要改node_modules里面的webpack配置文件？

**Comment by zhuiluo0987** [comment]
因为项目中好像只有angular-cli.josn。其他的webpack.common.js和systemjs.config.js没有啊

**Comment by xieziyu** [comment]
@zhuiluo0987 那只需要配置.angular-cli.json文件即可

**Comment by zhuiluo0987** [comment]
好的，谢谢
