### ISSUE TITLE
不支持Angular 6

### ISSUE THREAD

**Issue by chineseboytom** [xieziyu/ngx-echarts#88]
Angular 6使用了rxjs 6.x，而rxjs 6.x 的模块路径变化较大, 统一 import {...} from 'rxjs'。
进而导致ngx-echarts无法支持Angular 6。希望创建支持Angular 6的分支版本。

**Comment by xieziyu** [comment]
@chineseboytom 多谢，我会尽快上线

**Comment by xieziyu** [comment]
@chineseboytom 最新发布的v3.0.0 已支持Angular 6

**Comment by chineseboytom** [comment]
@xieziyu 非常感谢！

**Comment by buhuo00** [comment]
rxjs-compat  可以解决 <3 版本的错误，已试
