### ISSUE TITLE
請問可以增加其他events的功能嗎?

### ISSUE THREAD

**Issue by taipeiwu** [xieziyu/ngx-echarts#9]
例如pieselectchanged等等的功能，這是需要用於當selectedmode = single或multiple之用，感謝。

**Comment by xieziyu** [comment]
@taipeiwu 
`chartInit`能够暴露`echartsInstance`，因而可以直接利用`echartsInstance.on('pieselectchanged', (params) => { })`和`echartsInstance.off()`进行事件处理

echarts本身支持的events非常多，所以暂时没有计划增加新的emitter。

**Comment by taipeiwu** [comment]
@xieziyu , 謝謝，我看到了，這是非常好的解決方式，由衷感謝。

**Comment by jamessawyer** [comment]
请问在哪里能够获取到 echartsInstance呢？

**Comment by xieziyu** [comment]
@jamessawyer 在chartInit事件中可以获取到，请参考首页说明文档

**Comment by jamessawyer** [comment]
嗯嗯 已经看到了。还想问一下 获取到这个实例之后，如果我想监听别的事件，比如‘legendunselected’， 那么

this.chartInstance.on('legendunselected', (params) => {
      console.log('legend',params);
});

这段逻辑我应该放在哪里呢？
我放在点击事件中，点击图标上的 legend 好像并没用

**Comment by xieziyu** [comment]
@jamessawyer 你需要把注册侦听事件的逻辑放在chartInit里面。然后再在ngOnDestroy的时候取消侦听器。

**Comment by jamessawyer** [comment]
@xieziyu 好像还是没效果，这是我的代码
import { Component, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
	<div echarts [options]="chartOption" class="demo-chart" (chartInit)="onChartInit($event)" (chartClick)="onClick($event)"></div>
  `,
  styleUrls: [`
	.demo-chart {
		height: 400px;
   }
  `]
})
export class AppComponent implements OnDestroy {
  chartInstance: any;
  chartOption = {
    // ...  
  };

  onChartInit(ec) {
    this.chartInstance = ec;
    console.log('实例：', this.chartInstance);
    this.chartInstance.on('legendunselected', (params) => {
      console.log('legend', params);
    });
  }
  
  onClick(params: any) {
    console.log(params);
  }

  ngOnDestroy() {
    this.chartInstance.off('legendunselected');
  }
}

**Comment by xieziyu** [comment]
@jamessawyer 这个可能和echarts本身实现有关系，在你点击legend的时候，并没有dispatchAction 产生对应于legendselectchanged的事件。你可以尝试侦听legendselectchanged这个事件。鼠标点击图例的时候应该是dispatch了legendToggleSelect

**Comment by jamessawyer** [comment]
@xieziyu 嗯 对，写成legendselectchanged事件就ok了 十分感谢。现在还在echarts研究阶段，项目中马上要用，不知道会不会有什么别的坑

**Comment by huskylin** [comment]
感謝提問的人，受到幫助了
