### ISSUE TITLE
"export 'defineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by fengbean** [xieziyu/ngx-echarts#90]
![image](https://user-images.githubusercontent.com/31033272/39862318-05282f30-5476-11e8-8a94-f418ddf610f4.png)
请问为什么会报ngx-echarts.js的错

**Comment by xieziyu** [comment]
@fengbean 请提供angular的版本 和 ngx-echarts的版本号

**Comment by fengbean** [comment]
谢谢，找到原因了，因为我用的是ngzorro.6版本不好升级到angular6导致的
