### ISSUE TITLE
cannot-redeclare-block-scoped-variable-ngdevmode

### ISSUE THREAD

**Issue by tanxiao1977** [xieziyu/ngx-echarts#91]
你好 我安装的版本是ngx-echarts V2.1.0 ；
在app.module.ts 内 import { NgxEchartsModule } from 'ngx-echarts';

编译时报错 cannot-redeclare-block-scoped-variable-ngdevmode

不知道是什么原因，我的angular版本是5.5.6

`<img src=http://chuantu.biz/t6/308/1526003539x-1404817635.png />`
[http://chuantu.biz/t6/308/1526003539x-1404817635.png](url)

**Comment by fengbean** [comment]
谢谢，因为我用的ngzorro.6，不好升级到六导致的

**Comment by xieziyu** [comment]
@tanxiao1977 这个和angular的版本应该有关系。但是angular并没有5.5.6版本呀？

**Comment by tanxiao1977** [comment]
"@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "d3": "^5.1.0",
    "echarts": "^3.8.5",
    "mockjs": "^1.0.1-beta3",
    "ng-zorro-antd": "^0.6.15",
    "ngx-echarts": "^2.1.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"

不好意思  我看到的是rxjs版本是5.5.6的。。 angular是5.2.0

**Comment by xieziyu** [comment]
@tanxiao1977 angular的issues，了解一下：
https://github.com/angular/angular/issues/21925
