### ISSUE TITLE
版本命名

### ISSUE THREAD

**Issue by wangertu** [xieziyu/ngx-echarts#94]
既然支持了angular6了，索性把版本号也改成 6.0.0吧 ，洋气！

**Comment by xieziyu** [comment]
@wangertu 
抱歉唉，这个恐怕不行。
Angular的版本更新速度实在太快，而ngx-echarts相对稳定，在没有breaking change的情况下，理论上对angular版本是鲁棒的，不是很有必要跟着版本号走。
