### ISSUE TITLE
Cannot find name 'echarts'

### ISSUE THREAD

**Issue by fengbean** [xieziyu/ngx-echarts#99]
跑起来没问题，控制台也没报错，但是终端报错Cannot find name 'echarts'。用的版本都是最新的。
![image](https://user-images.githubusercontent.com/31033272/40649429-7c371a40-6363-11e8-8e2a-341a876afb1f.png)
![image](https://user-images.githubusercontent.com/31033272/40649513-b278397c-6363-11e8-906d-9a4e5ce6b176.png)

**Comment by xieziyu** [comment]
@fengbean 如果要使用全局echarts，你需要declare一下。建议用封装的service，详见说明文档。
